### ISSUE TITLE
功能：支持自定义 toolbar 和 hoverbar 的 图标 icon svg（已在 wangEditor-next 实现）

### ISSUE THREAD

**Issue by cycleccc** [wangeditor-next/wangEditor-next#13]
相关 issue：
https://github.com/wangeditor-team/wangEditor/issues/4429
https://github.com/wangeditor-team/wangEditor/issues/3710
https://github.com/wangeditor-team/wangEditor/issues/4395
https://github.com/wangeditor-team/wangEditor/issues/2278
https://github.com/wangeditor-team/wangEditor/issues/5816

**Comment by cycleccc** [comment]
已完成，可在 menu conf 中对对应的 toolbar 和 hoverbar key 加上 iconSvg 属性，填入对应的svg字符串，如
~~~javascript
  MEEN_CONF = {
  // toolbar 文字颜色 key
  color: {
    iconSvg:
      '<svg viewBox="0 0 1024 1024"><path d="M0 64v896h1024V64H0z m384 576v-192h256v192h-256z m256 64v192h-256v-192h256z m0-512v192h-256V192h256zM320 192v192H64V192h256z m-256 256h256v192H64v-192z m640 0h256v192h-256v-192z m0-64V192h256v192h-256zM64 704h256v192H64v-192z m640 192v-192h256v192h-256z"></path></svg>'
    ,
  },
  // hoverbar 图片宽度 key
  imageWidth30: {
    iconSvg: '<svg viewBox="0 0 1024 1024"><path d="M0 64v896h1024V64H0z m384 576v-192h256v192h-256z m256 64v192h-256v-192h256z m0-512v192h-256V192h256zM320 192v192H64V192h256z m-256 256h256v192H64v-192z m640 0h256v192h-256v-192z m0-64V192h256v192h-256zM64 704h256v192H64v-192z m640 192v-192h256v192h-256z"></path></svg>',
  },
}
~~~

**Comment by wjw020206** [comment]
> 已完成，可在 menu conf 中对对应的 toolbar 和 hoverbar key 加上 iconSvg 属性，填入对应的svg字符串，如
> 
> ```js
>   MEEN_CONF = {
>   // toolbar 文字颜色 key
>   color: {
>     iconSvg:
>       '<svg viewBox="0 0 1024 1024"><path d="M0 64v896h1024V64H0z m384 576v-192h256v192h-256z m256 64v192h-256v-192h256z m0-512v192h-256V192h256zM320 192v192H64V192h256z m-256 256h256v192H64v-192z m640 0h256v192h-256v-192z m0-64V192h256v192h-256zM64 704h256v192H64v-192z m640 192v-192h256v192h-256z"></path></svg>'
>     ,
>   },
>   // hoverbar 图片宽度 key
>   imageWidth30: {
>     iconSvg: '<svg viewBox="0 0 1024 1024"><path d="M0 64v896h1024V64H0z m384 576v-192h256v192h-256z m256 64v192h-256v-192h256z m0-512v192h-256V192h256zM320 192v192H64V192h256z m-256 256h256v192H64v-192z m640 0h256v192h-256v-192z m0-64V192h256v192h-256zM64 704h256v192H64v-192z m640 192v-192h256v192h-256z"></path></svg>',
>   },
> }
> ```

赞，刚需啊

**Comment by haoshifu** [comment]
请问在vue3中进行修改的方式是一样的吗

**Comment by cycleccc** [comment]
> 请问在vue3中进行修改的方式是一样的吗
> 
一样的
