### ISSUE TITLE
功能：添加格式刷功能（已在 wangEditor-next 实现）

### ISSUE THREAD

**Issue by cycleccc** [wangeditor-next/wangEditor-next#141]
相关 issue：
https://github.com/wangeditor-team/wangEditor/issues/5228
https://github.com/wangeditor-team/wangEditor/issues/5231
https://github.com/wangeditor-team/wangEditor/issues/5660
https://github.com/wangeditor-team/wangEditor/issues/4859
https://github.com/wangeditor-team/wangEditor/issues/2528

功能描述：
参考 wps 格式化实现

参考 wangEditor 实现:
https://github.com/hspprogrammer/wangeditor-formatPaint

**Comment by wjw020206** [comment]
格式刷的功能已经完成了 #143

**Comment by AndroidYzk** [comment]
格式刷功能仅复制了文字样式，没有办法复制段落样式，这个好像没有实现
