### ISSUE TITLE
Bug: microApp基座环境下报错 e10.removeAttr is not a function

### ISSUE THREAD

**Issue by haojiali** [wangeditor-next/wangEditor-next#144]
## bug 描述

microApp基座环境里进入页面报错e10.removeAttr is not a function，工具栏配置项没有了
![b79eceb566d3cc0f0596eb085f31c8f3b8e07600aecc48f3ccc2896fee874915QzpcVXNlcnNcQVNVU1xBcHBEYXRhXFJvYW1pbmdcRGluZ1RhbGtcMTMwODIxMTk0X3YyXEltYWdlRmlsZXNcMTcyNDEzNzE4NjcxMF83MjkzMDc0RC05MjY5LTRkNDMtQTFBMS1GQzg3MTI5MEQ3NkYucG5n](https://github.com/user-attachments/assets/800ee2f3-3c80-4735-84ac-70472870a320)

## 你预期的样子是？

能正常使用

## 系统和浏览器及版本号

- 操作系统---Windows
- 浏览器和版本--- Chrome

## wangEditor-next 版本

5.5.0

## demo 能否复现该 bug ？

不能

- demo https://cycleccc.github.io/demo/

## 在线 demo

- 沙盒链接: https://stackblitz.com/@cycleccc/collections/wangeditor

## 最小成本的复现步骤

- 步骤一
- 步骤二
- 步骤三

**Comment by cycleccc** [comment]
本地使用 micro [v1.0.0-rc.6](https://github.com/micro-zoe/micro-app/releases/tag/v1.0.0-rc.6) 测试 vue3 基座及 vue2 子应用 添加  editor demo 没有复现。🤯
会不会是打包配置的原因。

**Comment by liyangyangi** [comment]
请问解决了吗，碰到了相同的问题

**Comment by liyangyangi** [comment]
@cycleccc 
大佬 试试vite 项目吗 本地可以复现
基座vue3 vite项目，microapp 版本 v1.0.0-rc.6
子应用vue3 vite项目，
editor版本
"@wangeditor-next/editor": "^5.5.0"
"@wangeditor-next/editor-for-vue": "^5.1.14"

**Comment by cycleccc** [comment]
@liyangyangi 好的，方便给个 demo 仓库我 fork 复现不

**Comment by liyangyangi** [comment]
@cycleccc 好的 我晚点建个demo

**Comment by liyangyangi** [comment]
https://github.com/liyangyangi/micro-test1
@cycleccc 大佬这个仓库里两个项目跑起来就可以复现了
![fc9858cf-f450-4e4f-8b03-30ee70dffb52_capture](https://github.com/user-attachments/assets/562c3634-17c6-4152-a91e-20a48d215b6c)

**Comment by cycleccc** [comment]
@liyangyangi @haojiali 
是这里的问题
[micro-app-xxx 未定义](https://micro-zoe.github.io/micro-app/docs.html#/zh-cn/sandbox?id=undefined)
![image](https://github.com/user-attachments/assets/745dcdb6-6840-44cb-81a0-a94330d98f31)
切换为 window.xxx 可以渲染出来了

**Comment by liyangyangi** [comment]
@cycleccc 是在基座里手动设置修复的吗，设置了无效，全局搜索组件没有 var QUOTE_SVG

**Comment by haojiali** [comment]
> @cycleccc 是在基座里手动设置修复的吗，设置了无效，全局搜索组件没有 var QUOTE_SVG

你好，改好了吗

**Comment by liyangyangi** [comment]
> > @cycleccc 是在基座里手动设置修复的吗，设置了无效，全局搜索组件没有 var QUOTE_SVG
> 
> 你好，改好了吗
![image](https://github.com/user-attachments/assets/2e52352e-bb15-41d3-ab00-a949f6708d77)
没改好，你改好了吗
我按文档的设置无效，查代码安装包里没有 var QUOTE_SVG

**Comment by cycleccc** [comment]
> > > @cycleccc 是在基座里手动设置修复的吗，设置了无效，全局搜索组件没有 var QUOTE_SVG
> > 
> > 
> > 你好，改好了吗
> > ![image](https://private-user-images.githubusercontent.com/22519600/363024422-2e52352e-bb15-41d3-ab00-a949f6708d77.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ5ODY0MDAsIm5iZiI6MTcyNDk4NjEwMCwicGF0aCI6Ii8yMjUxOTYwMC8zNjMwMjQ0MjItMmU1MjM1MmUtYmIxNS00MWQzLWFiMDAtYTk0OWY2NzA4ZDc3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODMwVDAyNDgyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVmY2E2NDZjNmM5YWM4NmJhNTcxYWM1OTVkMWNkNzcxZGY1ZjYyNmQwMDg4N2M3MzE5OWY3ODVkM2E5MjllZDUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.9dorX0hmFOwToUIg1ZOcSaWcyK4UCpjvH5OmWr5AHEo)
> > 没改好，你改好了吗
> > 我按文档的设置无效，查代码安装包里没有 var QUOTE_SVG

https://www.npmjs.com/package/@wangeditor-next/editor/v/5.5.2-experimental.5
这个版本的代码没有做压缩，先用这个代替吧，具体怎么解决还得晚点再看看。

**Comment by haojiali** [comment]
> QUOTE_SVG

没有好呢，还是报错的

**Comment by cycleccc** [comment]
> > QUOTE_SVG
> 
> 没有好呢，还是报错的

正常发包的包都是压缩过的，我这里贴了没有压缩的包，可以试试 microapp 的遍历替换，且替换需要把所有 svg 都替换一遍。只能是暂时补丁，后续还是得想其它办法解决

**Comment by cycleccc** [comment]
可以切换 [5.5.3](https://www.npmjs.com/package/@wangeditor-next/editor/v/5.5.3) 试试
![image](https://github.com/user-attachments/assets/448a056d-bbeb-4f01-b162-08d736967d7e)

**Comment by haojiali** [comment]
首次加载报错
![lQLPJyBg-7axUj_NAU_NA5SwMGr-51oeQs4Gvf_YnvxQAA_916_335](https://github.com/user-attachments/assets/2c689405-dd6d-4647-b6fa-09295b68defb)
![lQLPJwWOTCIDmL_Mws0DsLDXOfmPI5Hixga9_57odT0A_944_194](https://github.com/user-attachments/assets/a2cd8e4d-dd98-4b7f-bf40-e4a661c0b9af)
![iwEcAqNwbmcDAQTRBaIF0QJoBrCNBbPhL1RNiga-AAFwEcEBB9IHzCxKCAAJomltCgAL0gABF_0 png_720x720q90](https://github.co
![iwEdAqNwbmcDAQTRBRUF0QJ1BrBuRI93FCFj7wa-AAFwEcEAB9IHzCxKCAAJomltCgAL0gABSfo png_720x720q90](https://github.com/user-attachments/assets/f26a440e-6240-448c-a03f-42aab16ecec7)
m/user-attachments/assets/2bd54873-6106-40a3-a26c-f8bda82fc855)

**Comment by liyangyangi** [comment]
> 可以切换 [5.5.3](https://www.npmjs.com/package/@wangeditor-next/editor/v/5.5.3) 试试 ![image](https://private-user-images.githubusercontent.com/62703840/363543105-448a056d-bbeb-4f01-b162-08d736967d7e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU2MTAxODgsIm5iZiI6MTcyNTYwOTg4OCwicGF0aCI6Ii82MjcwMzg0MC8zNjM1NDMxMDUtNDQ4YTA1NmQtYmJlYi00ZjAxLWIxNjItMDhkNzM2OTY3ZDdlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA2VDA4MDQ0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVjYmQ3NjA5YTQ0ZDQyM2ZjNzk3NjI1OWE2NTgwMWFjMjE2NjJjMzAxNmI1ODQzNWUyZGU4ZDdmNzFlMmY1N2ImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.YVODQZVPRtm2dm4gdFTmaj-4Ti0pO2VNHiGGE0avU3U)

大佬 这个问题应该是基座插件的问题，把基座的版本降到 v1.0.0-rc.5 就可以了，  升到6就有问题

**Comment by cycleccc** [comment]
> > 可以切换 [5.5.3](https://www.npmjs.com/package/@wangeditor-next/editor/v/5.5.3) 试试 ![image](https://private-user-images.githubusercontent.com/62703840/363543105-448a056d-bbeb-4f01-b162-08d736967d7e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU2MTAxODgsIm5iZiI6MTcyNTYwOTg4OCwicGF0aCI6Ii82MjcwMzg0MC8zNjM1NDMxMDUtNDQ4YTA1NmQtYmJlYi00ZjAxLWIxNjItMDhkNzM2OTY3ZDdlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA2VDA4MDQ0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVjYmQ3NjA5YTQ0ZDQyM2ZjNzk3NjI1OWE2NTgwMWFjMjE2NjJjMzAxNmI1ODQzNWUyZGU4ZDdmNzFlMmY1N2ImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.YVODQZVPRtm2dm4gdFTmaj-4Ti0pO2VNHiGGE0avU3U)
> 
> 大佬 这个问题应该是基座插件的问题，把基座的版本降到 v1.0.0-rc.5 就可以了， 升到6就有问题

嗯，感谢，这两天没跟进这个，5.5.3 打了个补丁虽然还有报错但至少能运行，深层的原因，还没确定。

**Comment by cycleccc** [comment]
已在 https://github.com/micro-zoe/micro-app/issues/1354 修复
