### ISSUE TITLE
Bug：工具栏在禁止状态时，点击图标还是能触发事件

### ISSUE THREAD

**Issue by flydeemon** [wangeditor-next/wangEditor-next#147]
## bug 描述

工具栏在禁止状态时，点击图标还是能触发事件

## 你预期的样子是？

在禁用状态时，禁止触发事件

## 系统和浏览器及版本号

- 操作系统
- 浏览器和版本

## demo 能否复现该 bug ？

能，用官网的例子可以复现

<img width="940" alt="image" src="https://github.com/user-attachments/assets/61dab233-66d9-476a-b2da-f2db67fed1f3">

**Comment by cycleccc** [comment]
在 [5.5.1版本](https://www.npmjs.com/package/@wangeditor-next/editor/v/5.5.1) 修复了这个问题
