### ISSUE TITLE
Bug：表格设置宽度自适应后无法拖动调整列宽

### ISSUE THREAD

**Issue by wjw020206** [wangeditor-next/wangEditor-next#150]
## bug 描述
![问题](https://github.com/user-attachments/assets/588e3d9b-eb15-43f0-8ed3-d74e6f016a4f)

在原版 wangEditor 中表格设置宽度自适应依旧可以拖动调整列宽

## 你预期的样子是？

表格设置宽度自适应后依旧可以拖动调整列宽

## 系统和浏览器及版本号

- Windows 10
- Google Chrome 128.0.6613.85

## wangEditor-next 版本

5.5.0

## demo 能否复现该 bug ？

能

## 最小成本的复现步骤

1. 创建一个表格
2. 将表格设置为宽度自适应
3. 尝试拖动调整表格的列宽

**Comment by cycleccc** [comment]
切换 [5.5.3](https://www.npmjs.com/package/@wangeditor-next/editor/v/5.5.3) 试试

**Comment by wjw020206** [comment]
> 切换 [5.5.3](https://www.npmjs.com/package/@wangeditor-next/editor/v/5.5.3) 试试

好的，我明天上班了试试，非常感谢

**Comment by wjw020206** [comment]
可以了，非常感谢
