### ISSUE TITLE
Bug：表格中多行文本，中间某一行文本加粗，会导致多了一行的效果，实际上预览正常，编辑器显示异常

### ISSUE THREAD

**Issue by caifu23** [wangeditor-next/wangEditor-next#152]
## Bug Description

*编辑器中插入表格之后，在某一个单元格输入几行文字，然后在中间一行加粗文本，就会导致加粗的上一行换行了。实际上获取到的预览代码正常，但是在编辑器中，会让人误解成换行了*
![Snipaste_2024-08-30_15-02-55](https://github.com/user-attachments/assets/8cfe24d8-e3a5-4a17-b809-a7c8e30dee54)
![image](https://github.com/user-attachments/assets/1cdecacc-5039-4cfa-89bc-45c6ff72a060)

## What did you expect to happen?

*希望编辑器不会显示多出来的一行空白*

## System, Browser, and Version

- 在demo上复现：https://cycleccc.github.io/demo/

## wangEditor-next Version

*Please enter the details...*

## Can the demo reproduce the bug?

Yes

- Demo: https://cycleccc.github.io/demo/

## Online Demo

 - SandBox url: https://stackblitz.com/@cycleccc/collections/wangeditor

## Steps to Reproduce at Minimum Cost

- Step 1
- Step 2
- Step 3

## relative issues
https://github.com/wangeditor-team/wangEditor/issues/5980

**Comment by HaibaraAiAPTX** [comment]
这个bug是因为在编辑模式下，表格内的换行是通过在文本中间插入\n来实现的，实际上在内部数据中，这三个行的元素还是同一个，当你将第二行的首字符加粗之后，在编辑器看来，文本的样式已经不一样了，已经不符合合并text元素的规则，所以元素就会被拆分成两个text元素，但是此时第一个元素的\n会被保留，在编辑器内，td元素被添加了css样式 [white-space: pre-wrap](https://developer.mozilla.org/zh-CN/docs/Web/CSS/white-space#pre-wrap)，也就是第一个text节点的\n实际上是会被渲染为换行，所以视觉上看起来就是中间多了一个空行。而在预览模式下\n是会被正常渲染为`<br/>`换行符，且text节点没有编辑模式下的众多span标签嵌套，并且没有 white-space: pre-wrap；所以在预览模式下看起来就是正常的。我在基于wangEditor开发的编辑器中是自行实现了一个表格，表格内的元素换行是正常的拆分成多个paragraph来实现的，但是editor内部是有限制一些块元素及inline元素的嵌套规则的，不符合规则的元素会被直接删除掉，所以也需要在normalizeNode节点中阻止掉一些元素的normalize的调用。过多的嵌套节点还会带来光标位置的处理问题，特别在多选情况下，光标在视觉上看起来是在同一个位置，但是实际上的point是不一样的，有可能在p>span的结尾，也有可能在p的结尾（包裹住了span）。光标位置的偏移会导致多选情况修改样式有时会修改不全，还会影响到slate内部关于拆分文本元素的逻辑，导致其他的bug，处理起来特别复杂。

**Comment by HaibaraAiAPTX** [comment]
还有一个简单的解决方案是，重写编辑器的insertBreak方法，判断是否在表格内，如果是在表格内就阻止原生insertBreak方法的执行，改为插入`\n\r`，默认实现是插入`\n`，这样视觉上看起来也是正常的
![Snipaste_2024-10-15_17-26-42](https://github.com/user-attachments/assets/a228b6b2-2bbc-4489-a813-c7573fb8dd6a)，但是如果你在第二行首执行删除就会只删除掉`\r`，所以看起来删除就会变成插入一个空行
![Snipaste_2024-10-15_17-28-16](https://github.com/user-attachments/assets/09fe3950-b35d-4fec-b2f5-3f1dfbde4bcd)，所以还需要在删除事件里面重写默认的拦截事件，判断如果光标的删除方向是向左还是向右，所要删除的方向的字符是否是`\n\r`，如果是就要删除掉这两个符号，如果不是就执行默认的删除逻辑。几个删除方法就是：deleteBackward、deleteForward、deleteFragment。其中deleteFragment是删除多选用的，还得判断是否只选中了一半，也就是光标在`\n\r`的中间，这种情况下就要修正光标把没选中的符号选中再执行默认的删除逻辑才能无残留的删除。

**Comment by cycleccc** [comment]
@HaibaraAiSherry 有兴趣处理一下不😀

**Comment by HaibaraAiAPTX** [comment]
> @HaibaraAiSherry 有兴趣处理一下不😀

可以，但是需要决定一下采用哪种解决方案，日常富文本的使用场景我觉得就是改成\n\r就够了

**Comment by cycleccc** [comment]
> 可以，但是需要决定一下采用哪种解决方案，日常富文本的使用场景我觉得就是改成\n\r就够了

有道理，第一种方案改动挺大，先第二种吧

**Comment by cycleccc** [comment]
已发布 5.6.4， [demo](https://cycleccc.github.io/demo/) 测试无误

**Comment by Miraiiiii** [comment]
> 已发布 5.6.4， [demo](https://cycleccc.github.io/demo/) 测试无误

好像回显的时候还是有问题，编辑的时候换行是没问题，但是输出的html还是
，导致保存回显之后还是会有换行
