### ISSUE TITLE
Vue3的Toolbar和Editor defaultConfig属性 不支持响应式数据吗

### ISSUE THREAD

**Issue by zcodecn** [wangeditor-next/wangEditor-next#153]
## bug 描述
 `<Toolbar 
        class="rich-text-editor__toolbar"
        :editor="editorRef"
        :defaultConfig="toolbarConfig" 
        :mode="mode"
    />`
 `
    <Editor
        class="rich-text-editor__body"
        v-model="modelData"
        :defaultConfig="editorConfig"
        :mode="mode" 
        @onCreated="handleCreated"
    />`
这里的toolbarConfig和editorConfig当使用计算属性时，数据变动了，编辑器配置没跟着变？难道不支持响应式吗？

## wangEditor-next 版本
  
 "@wangeditor-next/editor": "^5.5.1",
 "@wangeditor-next/editor-for-vue": "^5.1.14",

**Comment by cycleccc** [comment]
有具体的 demo 不，具体的需求是啥，在 文本发生改变或点击菜单的时候动态更改菜单配置吗

**Comment by cycleccc** [comment]
更改 toolbarConfig 和 editorConfig 要重建的时候才会生效，如 createEditor和createToolbar 时，具体代码如下：
> https://github.com/cycleccc/wangEditor-for-vue3/blob/main/src/components/Toolbar.vue

**Comment by zcodecn** [comment]
> 更改 toolbarConfig 和 editorConfig 要重建的时候才会生效，如 createEditor和createToolbar 时，具体代码如下：
> 
> > https://github.com/cycleccc/wangEditor-for-vue3/blob/main/src/components/Toolbar.vue

好吧，看来还是跟底层的wangEditor有关，要想响应各个配置变化，要么全部重建，要么调用api方法执行响应。
