### ISSUE TITLE
有序或者无序列表 选中列表项添加颜色，编辑器也给列表项的符号添加了颜色，实际预览符号是没有颜色的

### ISSUE THREAD

**Issue by caifu23** [wangeditor-next/wangEditor-next#154]
## bug 描述

*
有序或者无序列表 选中列表项添加颜色，编辑器也给列表项的符号添加了颜色，实际预览符号是没有颜色的
![Snipaste_2024-09-02_09-16-32](https://github.com/user-attachments/assets/3f3a1b1e-4586-4680-be06-240549d7772d)

*

## 你预期的样子是？

*请输入内容……*

## 系统和浏览器及版本号

- 操作系统
- 浏览器和版本

## wangEditor-next 版本

*请输入内容……*

## demo 能否复现该 bug ？

能/不能

- demo https://cycleccc.github.io/demo/

## 在线 demo

- 沙盒链接: https://stackblitz.com/@cycleccc/collections/wangeditor

## 最小成本的复现步骤

- 步骤一
- 步骤二
- 步骤三

**Comment by cycleccc** [comment]
发布了 [5.5.4](https://www.npmjs.com/package/@wangeditor-next/editor/v/5.5.4)  测试后没有问题可以关闭该 issue
