### ISSUE TITLE
功能：添加默认代码高亮语言配置

### ISSUE THREAD

**Issue by cycleccc** [wangeditor-next/wangEditor-next#155]
## 功能描述

在 [代码高亮](https://cycleccc.github.io/docs/guide/menu-config#%E4%BB%A3%E7%A0%81%E9%AB%98%E4%BA%AE) 配置中添加默认语言配置

相关 issue：
https://github.com/wangeditor-team/wangEditor/issues/4650

## 提炼几个功能点

- 添加默认代码高亮语言配置

## 原型图

~~~ typescript
editorConfig.MENU_CONF['codeSelectLang'] = {
    // 代码语言
    codeLangs: [
        { text: 'CSS', value: 'css', selected: true }, // 默认代码语言
        { text: 'HTML', value: 'html' },
        { text: 'XML', value: 'xml' },
        // 其他
    ]
}

~~~
在 此处添加默认语言配置

**Comment by Jusluo** [comment]
你好，这样好像不可以，是你建议的功能，但是还没有实现，是这样吗

**Comment by cycleccc** [comment]
@Jusluo 方便发下复现 demo 吗，这是以前实现并验证了没有测试的功能
