### ISSUE TITLE
Help：如何给 image 添加自定义数据属性 data-* 

### ISSUE THREAD

**Issue by Ling1992** [wangeditor-next/wangEditor-next#159]
## 问题描述

如何给 image 添加自定义数据属性 data-*  data-id
 
## wangEditor 版本

^5.5.3

## 是否查阅了文档 ？

文档链接 https://cycleccc.github.io/docs/

*是*

**Comment by cycleccc** [comment]
需要额外的自定义属性需要自定义元素，来兼容你需要的属性，具体看这里 [自定义结构](https://cycleccc.github.io/docs/guide/node-define)

[wangeditor-next](https://github.com/cycleccc/wangEditor-next) 内部解析 children 逻辑在此处https://github.com/cycleccc/wangEditor-next/blob/005435267e5d00e2e1d97aba33069a0820db4aeb/packages/core/src/parse-html/parse-common-elem-html.ts#L41

**Comment by yuwanchun** [comment]
作者大大，想问一下，如果自定义元素给img添加自定义属性的话，那设置的HTML tag，是新设置一个变量xx，还是依旧可以用img?
