### ISSUE TITLE
Bug：删除文字后，接着删除，表格单元格会被删除

### ISSUE THREAD

**Issue by ljp-777** [wangeditor-next/wangEditor-next#161]
## bug 描述

表格下方添加文案，然后从文案的中间开始删除，当文案全删除时，就会开始删除单元格

## 你预期的样子是？

禁止删除单个单元格

## 系统和浏览器及版本号

- mac
- chrome 127.0.6533.120

## wangEditor-next 版本

最新

## demo 能否复现该 bug ？

能

- demo https://cycleccc.github.io/demo/

## 在线 demo

- 沙盒链接: https://stackblitz.com/@cycleccc/collections/wangeditor

## 最小成本的复现步骤

https://github.com/user-attachments/assets/6654c076-48d3-4f0f-b985-224810d474b5

**Comment by cycleccc** [comment]
跟前段时间的一个优化相关，问题可能出现在此处
https://github.com/cycleccc/wangEditor-next/blob/0499f8ad1c3355070312dbb50f1a5de77ef61371/packages/table-module/src/module/plugin.ts#L97

**Comment by ljp-777** [comment]
确实，把代码恢复就好了，但不知道会不会带来其他问题
<img width="928" alt="image" src="https://github.com/user-attachments/assets/4032fbd9-fffd-4597-bd39-cbc757ac1656">

**Comment by cycleccc** [comment]
和这个修改有关 https://github.com/cycleccc/wangEditor-next/issues/51
可以看下能否兼容

**Comment by cycleccc** [comment]
发布了 [5.5.4](https://www.npmjs.com/package/@wangeditor-next/editor/v/5.5.4)  测试后没有问题可以关闭该 issue
