### ISSUE TITLE
Bug：只读模式下无法复制文本内容

### ISSUE THREAD

**Issue by wjw020206** [wangeditor-next/wangEditor-next#163]
## bug 描述

只读模式下无法复制文本内容

## 你预期的样子是？

只读模式下可以复制文本内容

## 系统和浏览器及版本号

- 操作系统：Windows 10
- 浏览器和版本：Chrome 128.0.6613.120

## wangEditor-next 版本

@wangeditor-next/editor: 5.5.4
@wangeditor-next/editor-for-vue2: 1.0.2

## demo 能否复现该 bug ？

不能，因为 demo 示例中没有只读模式的示例

## 在线 demo

复现示例：https://stackblitz.com/edit/vue2-vite-starter-syslwe?file=src%2Fcomponents%2FMyEditor.vue

## 最小成本的复现步骤

在异步设置内容后调用 `this.editor.disable()` 设置只读模式
```js
 mounted() {
    // 模拟 ajax 请求，异步渲染编辑器
    setTimeout(() => {
      this.html = '<p>我是 Ajax 异步设置内容 HTML，你可以选中我，但是无法复制我</p>'
      // 回显数据后设置编辑器为只读模式
      this.editor.disable()
    }, 1500)
  },
```

**Comment by huangzhang-ops** [comment]
我也遇到这个问题。请问解决了吗
