### ISSUE TITLE
运行在无界微前端子应用中

### ISSUE THREAD

**Issue by China-Htf** [wangeditor-next/wangEditor-next#166]
## bug 描述

回显的数据无法进行操作，必须要在富文本中输入一个字符

## 你预期的样子是？

回显的数据可删除

## 系统和浏览器及版本号

- window11
- 谷歌+ 128.0.6613.138

## wangEditor-next 版本

5.1.23

## demo 能否复现该 bug ？

不能

- demo https://cycleccc.github.io/demo/

## 报错信息
![image](https://github.com/user-attachments/assets/48d056cc-bc36-42f6-9a2e-68dce6c7d5bf)

**Comment by cycleccc** [comment]
能录个视频看下吗，需要更多的信息

**Comment by China-Htf** [comment]
> 能录个视频看下吗，需要更多的信息

一开始是原作者的组件，现在改成你这个，就解决了

**Comment by cycleccc** [comment]
OK，没问题的话可以关闭 issue 了
