### ISSUE TITLE
Bug：Table 中粘贴Excel或Word表格复制的数据问题

### ISSUE THREAD

**Issue by roydad** [wangeditor-next/wangEditor-next#171]
## bug 描述

从Excel或word表格中复制了一个区域数据，粘贴到Table控件中，没有按复制时的区域填充，而是把文本全部粘贴到同一个单元格中

## 你预期的样子是？

预期的样子应该是：按Excel或Word表格中复制选中区域粘贴填充数据，粘贴的数据单元格区域对应。

## 系统和浏览器及版本号

- 操作系统 Macos
- 浏览器和版本 Chrome 128.0.6613.138

## wangEditor-next 版本

wangeditor-next/editor-for-vue2": "^1.0.2"

## demo 能否复现该 bug ？

能

- demo https://stackblitz.com/edit/vue2-vite-starter-hkmsif?file=package.json

 
## 最小成本的复现步骤
- 步骤一 打开上述官方Demo，编辑器中插入一个随意大小的表格
- 步骤二 打开本机Excel，复制一个区域的数据（例如复制三行三列）
- 步骤三 选中在线Demo中表格的一个单元格，快捷键粘贴

**Comment by cycleccc** [comment]
有操作视频和对应的数据附件可以看下吗

**Comment by cycleccc** [comment]
缺少复现信息,待有更多复现信息再开启
