### ISSUE TITLE
wangEditor 升级成 wandEditor-next 表格卡死

### ISSUE THREAD

**Issue by panxin226** [wangeditor-next/wangEditor-next#172]
## 问题描述
为了使用表格合并问题，我把wangEditor 升级成了wandEditor-next ，打开之前wangEditor 做的表格，尝试拖拽之后页面卡死
*请输入遇到的问题...*

## wangEditor 版本

*请输入内容……*

## 是否查阅了文档 ？

（文档链接 [https://cycleccc.github.io/docs/](https://cycleccc.github.io/docs/) ）

*是/否*

## 最小成本的复现步骤

（请告诉我们，如何**最快的**复现该问题？）

- 步骤一
- 步骤二
- 步骤三

**Comment by cycleccc** [comment]
可以把相关的数据附件贴在这里，方便复现。

**Comment by panxin226** [comment]
> 可以把相关的数据附件贴在这里，方便复现。
[新文件 4.txt](https://github.com/user-attachments/files/17126853/4.txt)


https://github.com/user-attachments/assets/87077200-fe6d-4bf3-91c4-91ac821b372b

"<ul><li>数据特征</li></ul><table style="width: auto;table-layout: fixed;height:194"><colgroup contentEditable="false"><col width=180></col><col width=180></col><col width=180></col></colgroup><tbody><tr><td colspan="1" rowspan="1" width="556.82" style="border-width: 1px; border-style: solid; border-color: rgb(204, 204, 204);">数据模型</td><td colspan="1" rowspan="1" width="454.73" style="border-width: 1px; border-style: solid; border-color: rgb(204, 204, 204);">业务行为</td><td colspan="1" rowspan="1" width="485.57" style="border-width: 1px; border-style: solid; border-color: rgb(204, 204, 204);">数据特征</td></tr><tr><td colspan="1" rowspan="1" width="189" style="border-width: 1px; border-style: solid; border-color: rgb(204, 204, 204);"></td><td colspan="1" rowspan="1" width="189" style="border-width: 1px; border-style: solid; border-color: rgb(204, 204, 204);">例：新增</td><td colspan="1" rowspan="1" width="189" style="border-width: 1px; border-style: solid; border-color: rgb(204, 204, 204);">例：已经填写好配方的报价单，唯一主键：运营公司，需求编号，选型状态：2.已产生估价bom</td></tr></tbody></table><table style="width: auto;table-layout: fixed;height:0"><colgroup contentEditable="false"><col width=180></col><col width=180></col><col width=180></col><col width=180></col><col width=180></col><col width=180></col></colgroup><tbody><tr><th colSpan="1" rowSpan="1" width="auto" style=""></th><th colSpan="1" rowSpan="1" width="auto" style=""></th><th colSpan="1" rowSpan="1" width="auto" style=""></th><th colSpan="1" rowSpan="1" width="auto" style=""></th><th colSpan="1" rowSpan="1" width="auto" style=""></th><th colSpan="1" rowSpan="1" width="auto" style=""></th></tr><tr><td colspan="1" rowspan="1" width="auto" style="border-width: 1px; border-style: solid; border-color: rgb(204, 204, 204);"></td><td colspan="1" rowspan="1" width="auto" style="border-width: 1px; border-style: solid; border-color: rgb(204, 204, 204);"></td><td colspan="1" rowspan="1" width="auto" style="border-width: 1px; border-style: solid; border-color: rgb(204, 204, 204);"></td><td colspan="1" rowspan="1" width="auto" style="border-width: 1px; border-style: solid; border-color: rgb(204, 204, 204);"></td><td colspan="1" rowspan="1" width="auto" style="border-width: 1px; border-style: solid; border-color: rgb(204, 204, 204);"></td><td colspan="1" rowspan="1" width="auto" style="border-width: 1px; border-style: solid; border-color: rgb(204, 204, 204);"></td></tr><tr><td colspan="1" rowspan="1" width="auto" style="border-width: 1px; border-style: solid; border-color: rgb(204, 204, 204);"></td><td colspan="1" rowspan="1" width="auto" style="border-width: 1px; border-style: solid; border-color: rgb(204, 204, 204);"></td><td colspan="1" rowspan="1" width="auto" style="border-width: 1px; border-style: solid; border-color: rgb(204, 204, 204);"></td><td colspan="1" rowspan="1" width="auto" style="border-width: 1px; border-style: solid; border-color: rgb(204, 204, 204);"></td><td colspan="1" rowspan="1" width="auto" style="border-width: 1px; border-style: solid; border-color: rgb(204, 204, 204);"></td><td colspan="1" rowspan="1" width="auto" style="border-width: 1px; border-style: solid; border-color: rgb(204, 204, 204);"></td></tr><tr><td colspan="1" rowspan="1" width="auto" style="border-width: 1px; border-style: solid; border-color: rgb(204, 204, 204);"></td><td colspan="1" rowspan="1" width="auto" style="border-width: 1px; border-style: solid; border-color: rgb(204, 204, 204);"></td><td colspan="1" rowspan="1" width="auto" style="border-width: 1px; border-style: solid; border-color: rgb(204, 204, 204);"></td><td colspan="1" rowspan="1" width="auto" style="border-width: 1px; border-style: solid; border-color: rgb(204, 204, 204);"></td><td colspan="1" rowspan="1" width="auto" style="border-width: 1px; border-style: solid; border-color: rgb(204, 204, 204);"></td><td colspan="1" rowspan="1" width="auto" style="border-width: 1px; border-style: solid; border-color: rgb(204, 204, 204);"></td></tr><tr><td colspan="1" rowspan="1" width="auto" style="border-width: 1px; border-style: solid; border-color: rgb(204, 204, 204);"></td><td colspan="1" rowspan="1" width="auto" style="border-width: 1px; border-style: solid; border-color: rgb(204, 204, 204);"></td><td colspan="1" rowspan="1" width="auto" style="border-width: 1px; border-style: solid; border-color: rgb(204, 204, 204);"></td><td colspan="1" rowspan="1" width="auto" style="border-width: 1px; border-style: solid; border-color: rgb(204, 204, 204);"></td><td colspan="1" rowspan="1" width="auto" style="border-width: 1px; border-style: solid; border-color: rgb(204, 204, 204);"></td><td colspan="1" rowspan="1" width="auto" style="border-width: 1px; border-style: solid; border-color: rgb(204, 204, 204);"></td></tr><tr><td colspan="1" rowspan="1" width="auto" style="border-width: 1px; border-style: solid; border-color: rgb(204, 204, 204);"></td><td colspan="1" rowspan="1" width="auto" style="border-width: 1px; border-style: solid; border-color: rgb(204, 204, 204);"></td><td colspan="1" rowspan="1" width="auto" style="border-width: 1px; border-style: solid; border-color: rgb(204, 204, 204);"></td><td colspan="1" rowspan="1" width="auto" style="border-width: 1px; border-style: solid; border-color: rgb(204, 204, 204);"></td><td colspan="1" rowspan="1" width="auto" style="border-width: 1px; border-style: solid; border-color: rgb(204, 204, 204);"></td><td colspan="1" rowspan="1" width="auto" style="border-width: 1px; border-style: solid; border-color: rgb(204, 204, 204);"></td></tr><tr><td colspan="1" rowspan="1" width="auto" style="border-width: 1px; border-style: solid; border-color: rgb(204, 204, 204);"></td><td colspan="1" rowspan="1" width="auto" style="border-width: 1px; border-style: solid; border-color: rgb(204, 204, 204);"></td><td colspan="1" rowspan="1" width="auto" style="border-width: 1px; border-style: solid; border-color: rgb(204, 204, 204);"></td><td colspan="1" rowspan="1" width="auto" style="border-width: 1px; border-style: solid; border-color: rgb(204, 204, 204);"></td><td colspan="1" rowspan="1" width="auto" style="border-width: 1px; border-style: solid; border-color: rgb(204, 204, 204);"></td><td colspan="1" rowspan="1" width="auto" style="border-width: 1px; border-style: solid; border-color: rgb(204, 204, 204);"></td></tr></tbody></table><p><br></p>"

**Comment by cycleccc** [comment]
可以在 [demo](https://cycleccc.github.io/demo/) 重新测试，不会卡死了。

**Comment by panxin226** [comment]
> 可以在 [demo](https://cycleccc.github.io/demo/) 重新测试，不会卡死了。

谢谢！请问现在官网demo是哪个版本？是最新版5.5.5还是回退到5.5.4了啊？

**Comment by cycleccc** [comment]
官网是 5.5.6 官网 默认引用的最新版本
具体可以看 https://github.com/cycleccc/demo
或是 https://github.com/cycleccc/wangEditor-next/tree/master/packages/editor/demo
