### ISSUE TITLE
word文档复制文字加图片

### ISSUE THREAD

**Issue by panxin226** [wangeditor-next/wangEditor-next#174]
## 功能描述
建议新增从word里面拷贝文字+图片到编辑器里面，并且包含多张图片
*请输入内容……*
目前从word里面只能复制粘贴文字进去，图片要一张张复制粘贴进去，比较麻烦
## 提炼几个功能点

- 功能1 文字+图片
- 功能2 粘贴多张图片
- 功能3

## 原型图

*涉及到 UI 改动的功能，请一定提供原型图。原型图能表明功能即可，不要求规范和美观*

## 可参考的案例

*是否已有可参考的案例（如其他编辑器），有的话请给出链接*

**Comment by cycleccc** [comment]
https://github.com/wangeditor-team/wangEditor/issues/5593#issuecomment-2348320422
可以看下这个相关 issue

**Comment by panxin226** [comment]
> [wangeditor-team/wangEditor#5593 (comment)](https://github.com/wangeditor-team/wangEditor/issues/5593#issuecomment-2348320422) 可以看下这个相关 issue

好的，谢谢

**Comment by panxin226** [comment]
> [wangeditor-team/wangEditor#5593 (comment)](https://github.com/wangeditor-team/wangEditor/issues/5593#issuecomment-2348320422) 可以看下这个相关 issue
抱歉，我的意思是可以做到文字和图片
