### ISSUE TITLE
官网示例从word里面粘贴表格卡死

### ISSUE THREAD

**Issue by panxin226** [wangeditor-next/wangEditor-next#175]
## bug 描述

*请输入内容……*
从word里面粘贴表格过来，再从工具栏里面拉一个表格就会卡死
## 你预期的样子是？
不会卡死，都可以调整编辑
*请输入内容……*

## 系统和浏览器及版本号

- 操作系统
- 浏览器和版本

## wangEditor-next 版本
最新版本
*请输入内容……*

## demo 能否复现该 bug ？
能
能/不能

- demo https://cycleccc.github.io/demo/

## 在线 demo

- 沙盒链接: https://stackblitz.com/@cycleccc/collections/wangeditor

## 最小成本的复现步骤
从word里面粘贴表格，再从工具栏里面拉一个表格就会卡死
https://github.com/user-attachments/assets/1f946367-68b0-44ce-801e-b25b96c86104

- 步骤一
- 步骤二
- 步骤三

**Comment by cycleccc** [comment]
这个和 https://github.com/cycleccc/wangEditor-next/issues/172 同源，暂时不要使用 5.5.5 使用 5.5.4，晚点我会回滚。

**Comment by cycleccc** [comment]
官网默认引入的 最新 version ，和 #172  同源，可以在 #172 讨论
