### ISSUE TITLE
在不点击文本框，即没有焦点的情况下，工具栏可以不是禁用状态，可以点击按钮，默认插入下一行吗？

### ISSUE THREAD

**Issue by panxin226** [wangeditor-next/wangEditor-next#239]
## 问题描述

*请输入遇到的问题...*
在不点击文本框，即没有焦点的情况下，给工具栏可以不是禁用状态，可以点击默认插入下一行吗？就跟禅道里面一样
## wangEditor 版本

*请输入内容……*

## 是否查阅了文档 ？

（文档链接 [https://cycleccc.github.io/docs/](https://cycleccc.github.io/docs/) ）

*是/否*
是
## 最小成本的复现步骤
下面是禅道里面的，工具栏可以点击，默认就插进去内容
![image](https://github.com/user-attachments/assets/3057f723-200f-435c-9cd3-1a2cd707bf55)

（请告诉我们，如何**最快的**复现该问题？）

- 步骤一
- 步骤二
- 步骤三

**Comment by cycleccc** [comment]
https://github.com/cycleccc/wangEditor-next/blob/585612de9404b6331dfb4266ef84f4a445812715/packages/basic-modules/src/modules/common/menu/EnterMenu.ts#L26

wangEditor 按钮状态 通过 isDisabled 方法来控制，选区不为空是按钮能点击的基础条件。你可以在没有焦点时使用  editor.select 来选择一个选区以确保点击按钮能找到正确的选区来插入内容。

https://cycleccc.github.io/docs/guide/API#select


https://github.com/user-attachments/assets/a00fd037-e143-4143-a781-c6ceb809d4b3
