### ISSUE TITLE
功能：添加 table 合并功能（已在 wangEditor-next 实现）

### ISSUE THREAD

**Issue by cycleccc** [wangeditor-next/wangEditor-next#24]
相关 issue：
https://github.com/wangeditor-team/wangEditor/issues/5624
https://github.com/wangeditor-team/wangEditor/issues/4760
https://github.com/wangeditor-team/wangEditor/issues/3086

**Comment by jschyz** [comment]
<img src="https://github.com/cycleccc/wangEditor-next/assets/3281438/d548c65e-e8a7-4b98-9c1c-a5c2d33a09d1" width="350" />

已实现

**Comment by cycleccc** [comment]
麻烦能提个 pr 看一下吗😆，我们一起看下，合适的话就和进来了，需要这个功能的人还挺多的。

**Comment by rometw** [comment]
> ![2024-06-27 10 16 46](https://private-user-images.githubusercontent.com/3281438/343605260-d548c65e-e8a7-4b98-9c1c-a5c2d33a09d1.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk4MjQzMjksIm5iZiI6MTcxOTgyNDAyOSwicGF0aCI6Ii8zMjgxNDM4LzM0MzYwNTI2MC1kNTQ4YzY1ZS1lOGE3LTRiOTgtOWMxYy1hNWMyZDMzYTA5ZDEuZ2lmP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcwMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MDFUMDg1MzQ5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NmVhYzc4ZjFkYTBhNjBjYTFjZTA3NDM1MTQxZTJmODI3NDUyZjZiNWViNDIyMjg4YTFlMDhhYmJkYmE3YmY1MyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.HAsBhQoEeYm1oLwnaeui2n1trgC8lglDtImyfDuo25o) [ ![2024-06-27 10 16 46](https://private-user-images.githubusercontent.com/3281438/343605260-d548c65e-e8a7-4b98-9c1c-a5c2d33a09d1.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk4MjQzMjksIm5iZiI6MTcxOTgyNDAyOSwicGF0aCI6Ii8zMjgxNDM4LzM0MzYwNTI2MC1kNTQ4YzY1ZS1lOGE3LTRiOTgtOWMxYy1hNWMyZDMzYTA5ZDEuZ2lmP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcwMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MDFUMDg1MzQ5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NmVhYzc4ZjFkYTBhNjBjYTFjZTA3NDM1MTQxZTJmODI3NDUyZjZiNWViNDIyMjg4YTFlMDhhYmJkYmE3YmY1MyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.HAsBhQoEeYm1oLwnaeui2n1trgC8lglDtImyfDuo25o) ](https://private-user-images.githubusercontent.com/3281438/343605260-d548c65e-e8a7-4b98-9c1c-a5c2d33a09d1.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk4MjQzMjksIm5iZiI6MTcxOTgyNDAyOSwicGF0aCI6Ii8zMjgxNDM4LzM0MzYwNTI2MC1kNTQ4YzY1ZS1lOGE3LTRiOTgtOWMxYy1hNWMyZDMzYTA5ZDEuZ2lmP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcwMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MDFUMDg1MzQ5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NmVhYzc4ZjFkYTBhNjBjYTFjZTA3NDM1MTQxZTJmODI3NDUyZjZiNWViNDIyMjg4YTFlMDhhYmJkYmE3YmY1MyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.HAsBhQoEeYm1oLwnaeui2n1trgC8lglDtImyfDuo25o) [ ](https://private-user-images.githubusercontent.com/3281438/343605260-d548c65e-e8a7-4b98-9c1c-a5c2d33a09d1.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk4MjQzMjksIm5iZiI6MTcxOTgyNDAyOSwicGF0aCI6Ii8zMjgxNDM4LzM0MzYwNTI2MC1kNTQ4YzY1ZS1lOGE3LTRiOTgtOWMxYy1hNWMyZDMzYTA5ZDEuZ2lmP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcwMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MDFUMDg1MzQ5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NmVhYzc4ZjFkYTBhNjBjYTFjZTA3NDM1MTQxZTJmODI3NDUyZjZiNWViNDIyMjg4YTFlMDhhYmJkYmE3YmY1MyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.HAsBhQoEeYm1oLwnaeui2n1trgC8lglDtImyfDuo25o)
> 
> 已实现

千呼万唤的功能，感谢大佬

**Comment by cycleccc** [comment]
@rometw 大佬暂时还没提 pr ，没看到大佬的仓库和 npm 包，我回去看一下提到的这个[仓库](https://github.com/nlulic/slate-table/tree/f0429e857eeda2a5323ffb729d04bab84bcb159a) 复刻一下这个功能。

**Comment by jschyz** [comment]
这个功能合并+拆分都实现了，还在调整 拖动宽度 功能。

<img width="388" alt="image" src="https://github.com/cycleccc/wangEditor-next/assets/3281438/bb113edb-c0e4-480c-b122-5913c1c25953">

**Comment by jschyz** [comment]
<img width="359" alt="image" src="https://github.com/cycleccc/wangEditor-next/assets/3281438/a0124948-7aef-4f1b-b934-3326ee261212">

等我本周实现了，我在pr

**Comment by cycleccc** [comment]
OK，table 这一块比较复杂，幸苦了🙏🙏🙏

**Comment by jschyz** [comment]
![2024-07-02 20 33 08](https://github.com/cycleccc/wangEditor-next/assets/3281438/c8223c2d-cd96-48dc-bd20-18406184a737)

拖动宽度已实现，未来2天检查下Bug

**Comment by cycleccc** [comment]
收到，👍👍👍方便的话可以看看是否能覆盖到对应的单测，现在还没有上 github robot，这个后面也会补上。

**Comment by jschyz** [comment]
### WangEditor 支持 Table Cell 合并 [预览]

#### 基础能力
1. 拖动选择单元格，隐藏默认选区行为
2. 合并 / 拆分 单元格

<img src="https://github.com/cycleccc/wangEditor-next/assets/3281438/22a56aaf-f990-463d-abff-92e819821da3" width="350" />

#### 列拖拽
1. 表头出现单元格合并，每列可单独拖动设置宽度
2. 合并单元格内聚焦时，不会出现拖拽引导线

<img src="https://github.com/cycleccc/wangEditor-next/assets/3281438/f5d9911d-aed6-4b0d-81a5-a23bff0bce40" width="350" />

#### 行列新增 / 删除
1. 支持单元格区间内 新增 / 删除行列功能

<img src="https://github.com/cycleccc/wangEditor-next/assets/3281438/2dd9235d-50fe-481d-8486-3858806b0793" width="350" />

#### 宽度自适应
1. 当Table宽度100%时，拖动单元格能力禁用。

```
（无法判断单元格哪个该新增宽度，哪个该减小宽度）
``` 

<img src="https://github.com/cycleccc/wangEditor-next/assets/3281438/e292535b-68af-45cf-9070-f87b99948dd6" width="350" />

**Comment by cycleccc** [comment]
太赞了👍👍👍

**Comment by jschyz** [comment]
#### 图片自适应
1. 图片最大适应单元格 100% 宽度，不会存在撑大行为
2. 修改图片自身尺寸最大限制 🚫

<img src="https://github.com/cycleccc/wangEditor-next/assets/3281438/fa63bcd0-b1c7-44c8-a4be-e0c47a24d441" width="350" />

**Comment by jschyz** [comment]
修改点：
1. core 类里，拖拽影响点

`/package/core/src/text-area/syncSelection`
<img width="498" alt="image" src="https://github.com/cycleccc/wangEditor-next/assets/3281438/b3275602-c5af-4530-a916-d6ea797603f0">

`packages/core/src/editor/dom-editor.ts`
<img width="583" alt="image" src="https://github.com/cycleccc/wangEditor-next/assets/3281438/47f243ad-5c3d-4212-b751-e51fa95c32a2">

2. basic-modules 类修改 图片宽度等

`/package/basic-modules/src/modules/image/render-elem.tsx`
<img width="1132" alt="image" src="https://github.com/cycleccc/wangEditor-next/assets/3281438/fd7f9736-351a-458f-ad83-4a9713de9cc4">


table 合并单元格需要修改上面所示跨 package 文件，如可行，我就提交

**Comment by cycleccc** [comment]
可以提个 pr，我晚上回去看下，这两天在看输入法光标位置异常的 bug ，有点麻烦 。

**Comment by jschyz** [comment]
下周，改Bug改的要吐了，现在不能碰代码了

**Comment by cycleccc** [comment]
理解，祝周末愉快😂

**Comment by jschyz** [comment]
PR https://github.com/cycleccc/wangEditor-next/pull/31

没有尽善尽美，有很多关联没覆盖到，一起迭代吧

**Comment by jschyz** [comment]
> 修改点：
> 
> 1. core 类里，拖拽影响点
> 
> `/package/core/src/text-area/syncSelection` <img alt="image" width="498" src="https://private-user-images.githubusercontent.com/3281438/346055369-b3275602-c5af-4530-a916-d6ea797603f0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA1MTAxNzUsIm5iZiI6MTcyMDUwOTg3NSwicGF0aCI6Ii8zMjgxNDM4LzM0NjA1NTM2OS1iMzI3NTYwMi1jNWFmLTQ1MzAtYTkxNi1kNmVhNzk3NjAzZjAucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcwOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MDlUMDcyNDM1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MDFkOTU1MWU0OTMyN2RmNmQ0ZjU3MjIzOGExNDMxMGM0NzVmNzcxNWRmMzhjNGQ3NzdlNDgxZjhmMzgzMzA4MCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.sOXWebKYZaXA_r2QNpr_ss2un8JeKDHi7MBcIgRP3Rg">
> 
> `packages/core/src/editor/dom-editor.ts` <img alt="image" width="583" src="https://private-user-images.githubusercontent.com/3281438/346055892-47f243ad-5c3d-4212-b751-e51fa95c32a2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA1MTAxNzUsIm5iZiI6MTcyMDUwOTg3NSwicGF0aCI6Ii8zMjgxNDM4LzM0NjA1NTg5Mi00N2YyNDNhZC01YzNkLTQyMTItYjc1MS1lNTFmYTk1YzMyYTIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcwOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MDlUMDcyNDM1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YTJkNzRmNmQwNzU1YjNkYmQyZGZhZDY0ZjI4NjIyNmIyZGNiNGNlZWJmYzE2NDFhNjdmMTlhNGJlY2UwZjg3YyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.-ckWb1ipj11cOvHRfyHr8g-kpKOoYGirNHm4j5WF6qM">
> 

> 
> table 合并单元格需要修改上面所示跨 package 文件，如可行，我就提交


core package 修改的部分，解决了这个 issues

- https://github.com/wangeditor-team/wangEditor/issues/5292

- https://github.com/wangeditor-team/wangEditor/issues/5291

- https://github.com/wangeditor-team/wangEditor/issues/5603

**Comment by Chasonx911** [comment]
太棒了，感谢大佬，这个功能确实有很多用户迫切需要

**Comment by whsqjss** [comment]
合并后，使用getHTML获取html字符，再用setHTML回填，td中style="display:none"会被编辑器丢掉，导致合并掉的格子又会显示
![image](https://github.com/user-attachments/assets/7f6750ea-087d-4f69-bfc4-c96dca7c1f08)
