### ISSUE TITLE
Bug：更新最新版本5.5.8报错

### ISSUE THREAD

**Issue by io-o** [wangeditor-next/wangEditor-next#241]
## bug 描述

更新最新版本5.5.8报错

## 你预期的样子是？

修复

## 系统和浏览器及版本号

- macos
- chrome最新版

## wangEditor-next 版本

5.5.8

## demo 能否复现该 bug ？

能

- demo https://cycleccc.github.io/demo/

## 在线 demo

- 沙盒链接: https://stackblitz.com/edit/vue3-wangeditor-demo-8emmc7

## 最小成本的复现步骤

- 使用官方vue3在线demo
- 更新为5.5.8版本报错

**Comment by cycleccc** [comment]
以复现，请先暂时使用 5.5.7 ，5.5.8 做了较大的重构，待修复这个问题后，会做次版本升级

**Comment by cycleccc** [comment]
已修复，更新 5.6.0 即可。
