### ISSUE TITLE
图片无法回显，行内元素包含行内元素，无法解析

### ISSUE THREAD

**Issue by zhengzhishu** [wangeditor-next/wangEditor-next#253]
## Bug Description

*无法解析回显数据，图片回显失败*

## What did you expect to happen?

*以前的老数据（其他编辑器配置的）同步后，wangeditor无法解析回显数据，js报错，另外图片回显失败*

## System, Browser, and Version

- windows64，谷歌，
- Browser and Version

## wangEditor-next Version

*Please enter the details...*

## Can the demo reproduce the bug?

Yes/No

- Demo: https://cycleccc.github.io/demo/

## Online Demo

 - SandBox url: https://stackblitz.com/@cycleccc/collections/wangeditor

## Steps to Reproduce at Minimum Cost

- Step 1
- Step 2
- Step 3

**Comment by cycleccc** [comment]
有具体的可以复现的脱敏老数据吗

**Comment by zhengzhishu** [comment]
这是无法回显的图片的老数据


<div style=\"text-align:center;\"&gt;\r\n\t<img src=\"https://xxxxxxxxxx/0738.jpg\" width=\"800\" height=\"11317\" alt=\"\" /&gt; \r\n</div&gt;
中间是个网络图片地址




这个是无法解析文本的老数据


<p class=\"MsoNormal\" style=\"text-indent:32.0000pt;\"&gt;\r\n\t<span style=\"font-family:方正仿宋_GBK;font-size:16.0000pt;\"&gt;<span&gt;为进一步落实从严治党要求，强化党员干部的党性、法纪、廉洁意识，充分发挥好警示教育的震慑、教育作用。</span&gt;5月</span&gt;<span style=\"font-family:方正仿宋_GBK;font-size:16.0000pt;\"&gt;19</span&gt;<span style=\"font-family:方正仿宋_GBK;font-size:16.0000pt;\"&gt;<span&gt;日</span&gt;</span&gt;<span style=\"font-family:方正仿宋_GBK;font-size:16.0000pt;\"&gt;<span&gt;上午</span&gt;</span&gt;<span style=\"font-family:方正仿宋_GBK;font-size:16.0000pt;\"&gt;<span&gt;，</span&gt;</span&gt;<span style=\"font-family:方正仿宋_GBK;font-size:16.0000pt;\"&gt;<span&gt;市卫生服务中心</span&gt;</span&gt;<span style=\"font-family:方正仿宋_GBK;font-size:16.0000pt;\"&gt;<span&gt;党支部结合</span&gt;</span&gt;<span style=\"font-family:方正仿宋_GBK;font-size:16.0000pt;\"&gt;<span&gt;理论学习中心组（扩大）学习会议</span&gt;</span&gt;<span style=\"font-family:方正仿宋_GBK;font-size:16.0000pt;\"&gt;<span&gt;，组织</span&gt;</span&gt;<span style=\"font-family:方正仿宋_GBK;font-size:16.0000pt;\"&gt;<span&gt;全体中心组成员</span&gt;</span&gt;<span style=\"font-family:方正仿宋_GBK;font-size:16.0000pt;\"&gt;<span&gt;开展了</span&gt;“以案四说”警示教育活动。</span&gt;<span style=\"font-family:方正仿宋_GBK;font-size:16.0000pt;\"&gt;</span&gt;\r\n</p&gt;\r\n<p class=\"MsoNormal\" style=\"text-indent:32.0000pt;\"&gt;\r\n\t<span style=\"font-family:方正仿宋_GBK;font-size:16.0000pt;\"&gt;<span&gt;活动中，</span&gt;</span&gt;<span style=\"font-family:方正仿宋_GBK;font-size:16.0000pt;\"&gt;<span&gt;通报了</span&gt;</span&gt;<span style=\"font-family:方正仿宋_GBK;font-size:16.0000pt;\"&gt;<span&gt;市纪委公开曝光</span&gt;</span&gt;<span style=\"font-family:方正仿宋_GBK;font-size:16.0000pt;\"&gt;<span&gt;的</span&gt;</span&gt;<span style=\"font-family:方正仿宋_GBK;font-size:16.0000pt;\"&gt;4起违反中央八项规定精神</span&gt;<span style=\"font-family:方正仿宋_GBK;font-size:16.0000pt;\"&gt;<span&gt;的案例。中心党支部书记和</span&gt;</span&gt;<span style=\"font-family:方正仿宋_GBK;font-size:16.0000pt;\"&gt;3位支委委员</span&gt;<span style=\"font-family:方正仿宋_GBK;font-size:16.0000pt;\"&gt;<span&gt;结合自身工作实际</span&gt;</span&gt;<span style=\"font-family:方正仿宋_GBK;font-size:16.0000pt;\"&gt;<span&gt;分别</span&gt;</span&gt;<span style=\"font-family:方正仿宋_GBK;font-size:16.0000pt;\"&gt;<span&gt;从</span&gt;“德、责、法、纪”四个方面</span&gt;<span style=\"font-family:方正仿宋_GBK;font-size:16.0000pt;\"&gt;<span&gt;作了交流</span&gt;</span&gt;<span style=\"font-family:方正仿宋_GBK;font-size:16.0000pt;\"&gt;<span&gt;发言</span&gt;</span&gt;<span style=\"font-family:方正仿宋_GBK;font-size:16.0000pt;\"&gt;<span&gt;。他们在发言中</span&gt;</span&gt;<span style=\"font-family:方正仿宋_GBK;font-size:16.0000pt;\"&gt;<span&gt;深刻剖析身边发生的违法违纪典型案例，用身边事教育身边人，坚持做到防微杜渐，警钟长鸣。</span&gt;</span&gt;<span style=\"font-family:方正仿宋_GBK;font-size:16.0000pt;\"&gt;</span&gt;\r\n</p&gt;\r\n<p class=\"MsoNormal\" style=\"text-indent:32.0000pt;\"&gt;\r\n\t<span style=\"font-family:方正仿宋_GBK;font-size:16.0000pt;\"&gt;<span&gt;支部书记徐永柱同志在发言中指出：一要</span&gt;</span&gt;<span style=\"font-family:方正仿宋_GBK;font-size:16.0000pt;\"&gt;<span&gt;受警醒</span&gt;</span&gt;<span style=\"font-family:方正仿宋_GBK;font-size:16.0000pt;\"&gt;<span&gt;，加强责任意识；二要存戒惧，增强廉政意识；三要明底线，踏实履职尽责。这</span&gt;</span&gt;<span style=\"font-family:方正仿宋_GBK;font-size:16.0000pt;\"&gt;4起</span&gt;<span style=\"font-family:方正仿宋_GBK;font-size:16.0000pt;\"&gt;<span&gt;案件作为反面典型，提醒我们违法违纪的许多苗头和影子就存在我们身边，任何党员干部都不能有看客的侥幸心理，绝不可以事不关己、高高挂起，失责必问、问责必严也绝不是一句口号，必须始终把责任扛在肩上、牢记心头。</span&gt;</span&gt;<span style=\"font-family:方正仿宋_GBK;font-size:16.0000pt;\"&gt;</span&gt;\r\n</p&gt;\r\n<p class=\"MsoNormal\"&gt;\r\n\t<span style=\"font-family:方正仿宋_GBK;font-size:16.0000pt;\"&gt;<span&gt;身边鲜活的案例让</span&gt;</span&gt;<span style=\"font-family:方正仿宋_GBK;font-size:16.0000pt;\"&gt;<span&gt;参会人员</span&gt;</span&gt;<span style=\"font-family:方正仿宋_GBK;font-size:16.0000pt;\"&gt;<span&gt;都接受了一次思想和灵魂的洗礼，内心深受触动。大家纷纷表示，将以案为鉴，时刻保持清醒头脑，正确把握人生方向，自觉抵制各种诱惑，切实增强法纪观念和敬畏意识，筑牢拒腐防变的思想道德防线。</span&gt;</span&gt;\r\n</p&gt;
&nbsp;


黑炭
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年10月15日(星期二) 下午2:22
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [cycleccc/wangEditor-next] 图片无法回显，行内元素包含行内元素，无法解析 (Issue #253)














 
有具体的可以复现的脱敏老数据吗

**Comment by zhengzhishu** [comment]
<div style=\"text-align:center;\"&gt;\r\n\t<img src=\"https://xxx/UpLoadFiles/image/20220902/20220902092256_0738.jpg\" width=\"800\" height=\"11317\" alt=\"\" /&gt; \r\n</div&gt;




回显不了图片的
&nbsp;


黑炭
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年10月15日(星期二) 下午2:22
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [cycleccc/wangEditor-next] 图片无法回显，行内元素包含行内元素，无法解析 (Issue #253)














 
有具体的可以复现的脱敏老数据吗

**Comment by cycleccc** [comment]
这个数据有点乱，至少复制过来在 [在线HTML](https://www.jyshare.com/front-end/61/) 能显示才能说明这是合法的 HTML。

**Comment by zhengzhishu** [comment]
<div style=\"text-align:center;\">\r\n\t<img src=\"https://xxx.com/UpLoadFiles/image/20220902/20220902092256_0738.jpg\" width=\"800\" height=\"11317\" alt=\"\" /> \r\n</div>

这是图片无法回显的

**Comment by zhengzhishu** [comment]
> 这个数据有点乱，至少复制过来在 [在线HTML](https://www.jyshare.com/front-end/61/) 能显示才能说明这是合法的 HTML。

我邮件回复上来就变这样了，我页面里面用html标签能够正常解析

**Comment by cycleccc** [comment]
`<div style=\"text-align:center;\">\r\n\t<img src=\"https://xxx.com/UpLoadFiles/image/20220902/20220902092256_0738.jpg\" width=\"800\" height=\"11317\" alt=\"\" /> \r\n</div>`
![image](https://github.com/user-attachments/assets/cb80926d-8ab4-414f-94fc-5da224a2d1cd)

是这个样子吗

**Comment by zhengzhishu** [comment]
是的
&nbsp;


黑炭
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年10月15日(星期二) 下午2:37
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [cycleccc/wangEditor-next] 图片无法回显，行内元素包含行内元素，无法解析 (Issue #253)














 
<div style=\"text-align:center;\"&gt;\r\n\t<img src=\"https://xxx.com/UpLoadFiles/image/20220902/20220902092256_0738.jpg\" width=\"800\" height=\"11317\" alt=\"\" /&gt; \r\n</div&gt;
 image.png (view on web)
 
是这个样子吗

**Comment by zhengzhishu** [comment]
> `<div style=\"text-align:center;\">\r\n\t<img src=\"https://xxx.com/UpLoadFiles/image/20220902/20220902092256_0738.jpg\" width=\"800\" height=\"11317\" alt=\"\" /> \r\n</div>` ![image](https://private-user-images.githubusercontent.com/62703840/376486132-cb80926d-8ab4-414f-94fc-5da224a2d1cd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg5NzQ4MDgsIm5iZiI6MTcyODk3NDUwOCwicGF0aCI6Ii82MjcwMzg0MC8zNzY0ODYxMzItY2I4MDkyNmQtOGFiNC00MTRmLTk0ZmMtNWRhMjI0YTJkMWNkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDE1VDA2NDE0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMxYjhjNWE5ZjQzMzg2NDgyZmNlOGVhYzExNWFmNTIwYTY5M2VmMDk2Nzg1ZWRkNmJmMGYyZGJiOWI1MjAzNGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.j1f741VAGTkjVLvrdErIIgBGqmAz1Sv39A3-WToygcw)
> 
> 是这个样子吗

是的 就是那样，就是地址替换成可以访问的网络地址就可以了，我用html是能正常渲染的，包括前台也是正常显示的，就是后台配置点击修改，编辑器就无法解析了

**Comment by zhengzhishu** [comment]
> > `<div style=\"text-align:center;\">\r\n\t<img src=\"https://xxx.com/UpLoadFiles/image/20220902/20220902092256_0738.jpg\" width=\"800\" height=\"11317\" alt=\"\" /> \r\n</div>` ![image](https://private-user-images.githubusercontent.com/62703840/376486132-cb80926d-8ab4-414f-94fc-5da224a2d1cd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg5NzQ4MDgsIm5iZiI6MTcyODk3NDUwOCwicGF0aCI6Ii82MjcwMzg0MC8zNzY0ODYxMzItY2I4MDkyNmQtOGFiNC00MTRmLTk0ZmMtNWRhMjI0YTJkMWNkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDE1VDA2NDE0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMxYjhjNWE5ZjQzMzg2NDgyZmNlOGVhYzExNWFmNTIwYTY5M2VmMDk2Nzg1ZWRkNmJmMGYyZGJiOWI1MjAzNGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.j1f741VAGTkjVLvrdErIIgBGqmAz1Sv39A3-WToygcw)
> > 是这个样子吗
> 
> 是的 就是那样，就是地址替换成可以访问的网络地址就可以了，我用html是能正常渲染的，包括前台也是正常显示的，就是后台配置点击修改，编辑器就无法解析了

然后我放到你刚刚提供的在线html里面去，也是能够正常显示

**Comment by cycleccc** [comment]
大哥，别用 xxx.com 我随手复制一下，又中招了，在公司 OA 进了个黄网。可以把具体的数据放在  .txt 后缀的文件里，放在这个 issue 里，我晚上看看。 一般 html 能通过 [set-html](https://cycleccc.github.io/demo/set-html.html) 展示的就没有问题。

**Comment by zhengzhishu** [comment]
![数据](https://github.com/user-attachments/assets/d7404a25-54ff-493a-81e4-ab8933429340)

**Comment by zhengzhishu** [comment]
[data.txt](https://github.com/user-attachments/files/17375566/data.txt)

**Comment by zhengzhishu** [comment]
> 大哥，别用 xxx.com 我随手复制一下，又中招了，在公司 OA 进了个黄网。可以把具体的数据放在 .txt 后缀的文件里，放在这个 issue 里，我晚上看看。 一般 html 能通过 [set-html](https://cycleccc.github.io/demo/set-html.html) 展示的就没有问题。
好的 哥  辛苦了

这里面是两个配置的 一个是图片那个 一个是文本无法解析的那个  
[data.txt](https://github.com/user-attachments/files/17375647/data.txt)

**Comment by cycleccc** [comment]
第一个问题是老问题了，div套img导致显示不出来，解决方法是再注入 editor 前过滤一遍，把 img 标签外的 div 标签删掉。
第二个是前段时间为了兼容更多的格式衍生的 bug，现在正在处理，待发布新版本后可以测试。
这两个都是  HTML 格式的问题，只能是尽量兼容，毕竟 HTML 的格式太多样了

**Comment by zhengzhishu** [comment]
大佬，wangeditor-next没有集成wangeditor的设置默认字号的方法吗，从wangeditor改成wangeditor-next之后，设置默认字号不生效了
&nbsp;


黑炭
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年10月24日(星期四) 中午11:38
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [cycleccc/wangEditor-next] 图片无法回显，行内元素包含行内元素，无法解析 (Issue #253)














 
Closed #253 as completed via #283.
