### ISSUE TITLE
Bug:  在 vite\vue3 项目中使用报错

### ISSUE THREAD

**Issue by DejaVuuuuuuu** [wangeditor-next/wangEditor-next#256]
## bug 描述

*请输入内容……*
![image](https://github.com/user-attachments/assets/b4210d68-e850-4ee0-8217-f665d880cb3c)

我按照示例建了个空项目，引用组件后使用直接报错;
![image](https://github.com/user-attachments/assets/2b9967ef-5cd7-4a40-8272-03494b0dbbf8)

## 你预期的样子是？

*请输入内容……*

## 系统和浏览器及版本号

- 操作系统
- 浏览器和版本
最新版谷歌浏览器哦
## wangEditor-next 版本

*请输入内容……*

## demo 能否复现该 bug ？

能/不能

- demo https://cycleccc.github.io/demo/

## 在线 demo

- 沙盒链接: https://stackblitz.com/edit/vitejs-vite-wy9zim?file=src%2Fcomponents%2FHelloWorld.vue&terminal=dev

## 最小成本的复现步骤

- 步骤一
- npm安装报错
![image](https://github.com/user-attachments/assets/bc741391-a6ca-453b-9828-849d177e1afe)

- 步骤二
- 步骤三

**Comment by DejaVuuuuuuu** [comment]
@cycleccc  麻烦大佬修复了说一声

**Comment by cycleccc** [comment]
发布了 5.6.2-beta，上午试了没问题，可以切换试试

**Comment by cycleccc** [comment]
你的 vite demo 没有显示引入 style.css 这个记得加一下
~~~
import '@wangeditor-next/editor/dist/css/style.css';
~~~

**Comment by cycleccc** [comment]
已发布 5.6.2

**Comment by DejaVuuuuuuu** [comment]
> 你的 vite demo 没有显示引入 style.css 这个记得加一下
> 
> ```
> import '@wangeditor-next/editor/dist/css/style.css';
> ```

好的 感谢大佬
