### ISSUE TITLE
5.6.1在linux系统上报错

### ISSUE THREAD

**Issue by huangzhang-ops** [wangeditor-next/wangEditor-next#257]
## Bug Description

![image](https://github.com/user-attachments/assets/b4b3c714-e76e-458f-aad5-928064211b03)

## What did you expect to happen?

*Please enter the details...*

## System, Browser, and Version

- Operating System
- Browser and Version

## wangEditor-next Version

*Please enter the details...*

## Can the demo reproduce the bug?

Yes/No

- Demo: https://cycleccc.github.io/demo/

## Online Demo

 - SandBox url: https://stackblitz.com/@cycleccc/collections/wangeditor

## Steps to Reproduce at Minimum Cost

- Step 1
- Step 2
- Step 3

**Comment by cycleccc** [comment]
重复 bug
https://github.com/cycleccc/wangEditor-next/issues/256
已在 5.6.2 解决。
