### ISSUE TITLE
TODO：添加使用文档

### ISSUE THREAD

**Issue by cycleccc** [wangeditor-next/wangEditor-next#26]
在网上看到不少吐槽 wangEditor 文档不清晰的言论，我想试试，解决或改善它。

**Comment by jschyz** [comment]
看了下，好多拿来主义。 我主要一个合并单元格功能，这样我就能从 ueditor 迁移到 wangeditor 了

**Comment by cycleccc** [comment]
能像老哥这样动手能力强的不多的，大多数能做到心平气和认真讨论问题就很好了😆

**Comment by cycleccc** [comment]
已在github.io部署[使用文档](https://cycleccc.github.io/docs/)及[demo](https://cycleccc.github.io/demo/)
