### ISSUE TITLE
讨论：在表格编辑框里不能添加表格

### ISSUE THREAD

**Issue by panxin226** [wangeditor-next/wangEditor-next#261]
## 问题描述
你好，请问一下表格里面是不可以再插入表格了吗？但是有时候在表格外也不行

*请输入遇到的问题...*
![image](https://github.com/user-attachments/assets/f9d4edcb-764e-4664-998a-d444282605ea)

## wangEditor 版本

*请输入内容……*

## 是否查阅了文档 ？

（文档链接 [https://cycleccc.github.io/docs/](https://cycleccc.github.io/docs/) ）

*是/否*
是
## 最小成本的复现步骤

（请告诉我们，如何**最快的**复现该问题？）

- 步骤一
- 步骤二
- 步骤三

**Comment by cycleccc** [comment]
表格嵌套想想都很复杂，光标在表格内时会禁止插入表格。至于在表格外也不行这个有具体的HTML或JSON数据吗

**Comment by cycleccc** [comment]
图里的就是错误的在表格中插入了表格的样子，多出现于只有一个 table 元素然后全选复制粘贴，此时会无法识别到正确的选区导致没有删除原来的元素，在原来的table上插入table。
