### ISSUE TITLE
建议修改一下编辑区内 有序列表和无序列表 的间隙

### ISSUE THREAD

**Issue by xb1357686** [wangeditor-next/wangEditor-next#263]
## 功能描述

希望编辑的时候能和预览的样式一致， 或者开放一些className 之类的，可以用户样式覆盖

![image](https://github.com/user-attachments/assets/a1723b7f-8b20-4c08-b79d-fe0a255f3fd7)

目前看dom结构有点不一样

**Comment by cycleccc** [comment]
编辑器内的 list 是用字符模拟的，内置UI好改，className 这个是很有必要，已经在 TodoList 里了。
https://github.com/cycleccc/wangEditor-next/issues/25
