### ISSUE TITLE
设置单元格宽度会导致左边框丢失，另外建议增加表格单个单元格多行文本的居中居左居中居右功能，现在设置单个单元格内的内容是整体跟着居中，居左

### ISSUE THREAD

**Issue by Xiaodonghao-web** [wangeditor-next/wangEditor-next#265]
## 功能描述

*请输入内容……*1

## 提炼几个功能点

- 功能1
- 功能2
- 功能3

## 原型图

*涉及到 UI 改动的功能，请一定提供原型图。原型图能表明功能即可，不要求规范和美观*

## 可参考的案例

*是否已有可参考的案例（如其他编辑器），有的话请给出链接*
![WechatIMG3](https://github.com/user-attachments/assets/f815e2cd-af3d-4b55-840b-0bbed9702a68)

![WechatIMG2](https://github.com/user-attachments/assets/bab18aac-7071-4df7-9007-3f33f7294bd5)

**Comment by cycleccc** [comment]
表格单个单元格多行文本的居中居左居中居右功能这个需要比较大的改动，先记下，后续再优化。
