### ISSUE TITLE
拆分单元格报错

### ISSUE THREAD

**Issue by han-z-x** [wangeditor-next/wangEditor-next#279]
## bug 描述

*合并单元格后再执行才分单元格操作时报错*
![image](https://github.com/user-attachments/assets/cd422d08-a877-4042-8eed-3d212b69c594)

## 你预期的样子是？

*能够正常拆分*

## 系统和浏览器及版本号

- 操作系统 
- 浏览器和版本 Google Chrome 版本 127.0.6533.73（正式版本） （64 位）

## wangEditor-next 版本

*5.6.4*

## demo 能否复现该 bug ？

不能

- demo https://cycleccc.github.io/demo/

## 在线 demo

- 沙盒链接: https://stackblitz.com/@cycleccc/collections/wangeditor

## 最小成本的复现步骤

- 步骤一
- 步骤二
- 步骤三

**Comment by cycleccc** [comment]
信息不足，得有视频才能知道怎么操作的，有最小复现demo才更好定位代码bug。
