### ISSUE TITLE
你好作者大大，我这边回显上有点问题想问一下

### ISSUE THREAD

**Issue by zyj2077** [wangeditor-next/wangEditor-next#286]
## 问题描述

<img src=\"{_XD}/标特/image/1729750472900-g93p4zfcrsn.png\" alt=\"1729750472900-g93p4zfcrsn.png\" data-href=\"\" style=\"width: 532.00px;height: 354.66px;float: right;\"/>

当前富文本的元素，使用的插件的浮动效果

但是，在设置编辑器回显的时候，浮动效果会自动清除，这个怎么处理好一些

**Comment by cycleccc** [comment]
浮动效果清除是指 float 属性丢失吧，属性处理一般是在 parseElemsHtml 里处理，你可以 debug看看对应的 image elem 里有没有 float 属性。

**Comment by zyj2077** [comment]
在导出的时候是有相应样式的，就是讲导出的html格式再次导入的时候，就没有了。editor.dangerouslyInsertHtml(html)  和setHtml两个都是过，一样      parseElemsHtml   这个在哪呀

**Comment by zyj2077** [comment]
> 在导出的时候是有相应样式的，就是讲导出的html格式再次导入的时候，就没有了。editor.dangerouslyInsertHtml(html) 和setHtml两个都是过，一样 parseElemsHtml 这个在哪呀

在导出的时候是有相应样式的，就是讲导出的html格式再次导入的时候，就没有了。editor.dangerouslyInsertHtml(html) 和setHtml两个都是过，一样 parseElemsHtml 这个在哪呀

**Comment by cycleccc** [comment]
导出没问题那就是解析的问题，parseElemsHtml 是自定义的插件里用来处理编辑区样式的模块，类似这里
https://github.com/hqwlkj/wangEditor-plugin-float-image/blob/6476947de2b20e39848cb8f607ebd1189d782c77/src/module/parse-elem-html.ts#L11

**Comment by cycleccc** [comment]
得要 debug 看一下具体哪里没解析到

**Comment by zyj2077** [comment]
问个萌新问题，这个怎么进行debug，在f12 上吗？还是在代码编辑器上？

**Comment by zyj2077** [comment]
> 导出没问题那就是解析的问题，parseElemsHtml 是自定义的插件里用来处理编辑区样式的模块，类似这里 https://github.com/hqwlkj/wangEditor-plugin-float-image/blob/6476947de2b20e39848cb8f607ebd1189d782c77/src/module/parse-elem-html.ts#L11

这个没看懂他具体可以怎么用，这边也是用的这个插件，但是这个方法貌似是在编辑区域，进行格式转换的一个方法

**Comment by cycleccc** [comment]
> 问个萌新问题，这个怎么进行debug，在f12 上吗？还是在代码编辑器上？

在浏览器里找到对应的插件代码打断点

**Comment by cycleccc** [comment]
> > 导出没问题那就是解析的问题，parseElemsHtml 是自定义的插件里用来处理编辑区样式的模块，类似这里 https://github.com/hqwlkj/wangEditor-plugin-float-image/blob/6476947de2b20e39848cb8f607ebd1189d782c77/src/module/parse-elem-html.ts#L11
> 
> 这个没看懂他具体可以怎么用，这边也是用的这个插件，但是这个方法貌似是在编辑区域，进行格式转换的一个方法

是的，解析对应 dom 元素获取属性，返回 children content 格式

**Comment by zyj2077** [comment]
> > > 导出没问题那就是解析的问题，parseElemsHtml 是自定义的插件里用来处理编辑区样式的模块，类似这里 https://github.com/hqwlkj/wangEditor-plugin-float-image/blob/6476947de2b20e39848cb8f607ebd1189d782c77/src/module/parse-elem-html.ts#L11
> > 
> > 
> > 这个没看懂他具体可以怎么用，这边也是用的这个插件，但是这个方法貌似是在编辑区域，进行格式转换的一个方法
> 
> 是的，解析对应 dom 元素获取属性，返回 children content 格式

![image](https://github.com/user-attachments/assets/133417d0-841f-4598-80e1-e6142bef06b7)
![image](https://github.com/user-attachments/assets/8150b850-1a3b-462e-80e6-df77c04e41f6)
zai在走到这里的时候图片会显示出来

**Comment by zyj2077** [comment]
但是没找到相对应的处理代码

**Comment by cycleccc** [comment]
去找 下载的插件里对应的 parseElemsHtml  代码

**Comment by cycleccc** [comment]
添加了 float image 插件 https://www.npmjs.com/package/@wangeditor-next/plugin-float-image

**Comment by cycleccc** [comment]
给 wangEditor float image plugin 提了 pr https://github.com/hqwlkj/wangEditor-plugin-float-image/pull/13
