### ISSUE TITLE
同时在编辑器中复制文字+图片，图片会丢失

### ISSUE THREAD

**Issue by panxin226** [wangeditor-next/wangEditor-next#290]
## Bug Description
同时在编辑器中复制文字+图片，图片会丢失，但是全选复制粘贴可以，可以在官网示例里面复现。
*Please enter the details...*

https://github.com/user-attachments/assets/3a04fd99-0403-4de2-9c94-1aafce2955cc

## What did you expect to happen?

*Please enter the details...*

## System, Browser, and Version

- Operating System
- Browser and Version

## wangEditor-next Version
最新版
*Please enter the details...*

## Can the demo reproduce the bug?

Yes/No

- Demo: https://cycleccc.github.io/demo/

## Online Demo

 - SandBox url: https://stackblitz.com/@cycleccc/collections/wangeditor

## Steps to Reproduce at Minimum Cost

- Step 1
- Step 2
- Step 3

**Comment by cycleccc** [comment]
全选 、鼠标选择、shift 选择，ctrl+c  和  ctrl+x 都试了没复现

**Comment by panxin226** [comment]
> 全选 、鼠标选择、shift 选择，ctrl+c 和 ctrl+x 都试了没复现

是鼠标去选择之后再复制粘贴有问题
https://github.com/user-attachments/assets/2acd4d09-1046-4504-a38c-ae40ba1b1458

**Comment by panxin226** [comment]
> 全选 、鼠标选择、shift 选择，ctrl+c 和 ctrl+x 都试了没复现

我知道怎么复现了，全选的时候多了这个空格，所以粘贴没问题，如果单击选中不多拉一个空格就不行
![image](https://github.com/user-attachments/assets/a1c6c4e4-0603-4568-ab01-83755f187d1f)
![image](https://github.com/user-attachments/assets/c0a557d3-6d5b-4ac6-b397-932923afc84e)
