### ISSUE TITLE
从文档里面复制文字加图片，图片会丢失

### ISSUE THREAD

**Issue by panxin226** [wangeditor-next/wangEditor-next#310]
## bug 描述
从文档里面复制文字加图片，图片会丢失
*请输入内容……*

## 你预期的样子是？
从文档里面复制文字加图片，文字和图片都会粘贴进去
*请输入内容……*

## 系统和浏览器及版本号

- 操作系统
- 浏览器和版本
chrome 最新版
## wangEditor-next 版本
最新版
*请输入内容……*

## demo 能否复现该 bug ？
能
能/不能

- demo https://cycleccc.github.io/demo/

## 在线 demo
官网demo可复现

- 沙盒链接: https://stackblitz.com/@cycleccc/collections/wangeditor

## 最小成本的复现步骤

- 步骤一
- 步骤二
- 步骤三

https://github.com/user-attachments/assets/50c6cbdf-0a99-4369-9331-8a5e47fc0e2e

**Comment by cycleccc** [comment]
是否是重复issue？
https://github.com/wangeditor-team/wangEditor/issues/5593#issuecomment-2348320422

**Comment by panxin226** [comment]
参考这个文档可以实现  https://blog.csdn.net/assokoo123/article/details/126034566
