### ISSUE TITLE
同时在word里面复制多张图片不能粘贴进编辑器里面

### ISSUE THREAD

**Issue by panxin226** [wangeditor-next/wangEditor-next#311]
## bug 描述

*请输入内容……*
您好，我在word里面可以复制一张图片到编辑器，但是同时在word里面复制多张图片不能粘贴进编辑器里面
## 你预期的样子是？
可以复制多张图片到编辑器
*请输入内容……*

## 系统和浏览器及版本号

- 操作系统
- 浏览器和版本
chrome最新版
## wangEditor-next 版本
最新版
*请输入内容……*

## demo 能否复现该 bug ？

能/不能
能
- demo https://cycleccc.github.io/demo/

## 在线 demo
官网可测试

- 沙盒链接: https://stackblitz.com/@cycleccc/collections/wangeditor

## 最小成本的复现步骤

- 步骤一
- 步骤二
- 步骤三

https://github.com/user-attachments/assets/9af27597-3cab-488e-8b4c-1846624fff8b

**Comment by cycleccc** [comment]
https://github.com/wangeditor-team/wangEditor/issues/5593#issuecomment-2348320422
有空白占位图片的话应该可以通过替换 src 解决，需要同时兼容 wps和Microsoft ，我最近会看一下 Microsoft office 下的情况。

**Comment by panxin226** [comment]
> [wangeditor-team/wangEditor#5593 (comment)](https://github.com/wangeditor-team/wangEditor/issues/5593#issuecomment-2348320422) 有空白占位图片的话应该可以通过替换 src 解决，需要同时兼容 wps和Microsoft ，我最近会看一下 Microsoft office 下的情况。

关键这个怎么替换file:///的值啊？我们单个图片是直接上传到服务器里面的
![image](https://github.com/user-attachments/assets/af391580-c1e8-48b8-b860-a309c4adcddf)

**Comment by cycleccc** [comment]
试试这个 API  [parseImageSrc](https://cycleccc.github.io/docs/guide/menu-config#%E5%9B%BE%E7%89%87)
