### ISSUE TITLE
在自定义按钮时插入了一个 空格字符 但是变成了换行 div

### ISSUE THREAD

**Issue by along521** [wangeditor-next/wangEditor-next#314]
## bug 描述

在自定义按钮时插入了一个 空格字符 但是变成了换行 div

## 你预期的样子是？

正常的插入一个字符 或 样式正确也行。

## 系统和浏览器及版本号

- macos 15
- 谷歌最新

## wangEditor-next 版本
   "@wangeditor-next/editor": "^5.6.7",
   "@wangeditor-next/editor-for-vue": "^5.1.14",

## demo 能否复现该 bug ？

不能

## 最小成本的复现步骤

代码如下 插入到字符会变成div  &emsp; 和 \u3000 都不行

import {  IButtonMenu, IDomEditor, DomEditor } from "@wangeditor-next/editor";

export default class SpaceButtonMenu implements IButtonMenu {
  title: string;
  tag: string;
  constructor() {
    this.title = "空格(日文)"; // 自定义菜单标题
    this.tag = "button";
  }

  // 获取菜单执行时的 value ，用不到则返回空 字符串或 false
  getValue(editor: IDomEditor): string | boolean {
    return false; // &emsp;
  }

  // 菜单是否需要激活（如选中加粗文本，“加粗”菜单会激活），用不到则返回 false
  isActive(editor: IDomEditor): boolean {
    return false;
  }

  // 菜单是否需要禁用（如选中 H1 ，“引用”菜单被禁用），用不到则返回 false
  isDisabled(editor: IDomEditor): boolean {
    return false;
  }

  // 点击菜单时触发的函数
  exec(editor: IDomEditor, value: string | boolean) {
    // JS 语法
    if (this.isDisabled(editor)) return;
    const node = {
      type: "japspace",
      // children: [{ text: "&emsp;" }],
      children: [{ text: "\u3000" }],
    };
    editor?.insertNode(node);
    console.log(editor.getHtml());
    // editor.insertText(value as string); // value 即 this.value(editor) 的返回值
  }
}

// 空格-日文
export const japSpaceMenu = {
  key: "SpaceMenuKey", // 定义 menu key ：要保证唯一、不重复（重要）
  factory() {
    return new SpaceButtonMenu();
  },
};

**Comment by cycleccc** [comment]
这个应该算是 question 不是 bug，方便的话给一个最小复现沙盒demo，需要解决的问题很多🙏🙏

**Comment by along521** [comment]
目前该问题 在项目中，不太好拆出来。如无法解决 能否给出 自定义按键 的空格 是大空格的实现方案

**Comment by along521** [comment]
> 这个应该算是 question 不是 bug，方便的话给一个最小复现沙盒demo，需要解决的问题很多🙏🙏

目前该问题 在项目中，不太好拆出来。如无法解决 能否给出 自定义按键 的空格 是大空格的实现方案
