### ISSUE TITLE
自定义按钮 插入的元素无法生效

### ISSUE THREAD

**Issue by along521** [wangeditor-next/wangEditor-next#315]
## 问题描述

自定义按钮 插入的元素无法生效 变成div
能否给提供给 大空格的解决方案。日文需要使用大空格。

## wangEditor 版本

    "@wangeditor-next/editor": "^5.6.7",
    "@wangeditor-next/editor-for-vue": "^5.1.14",

## 是否查阅了文档 ？

是

## 最小成本的复现步骤

  // 点击菜单时触发的函数
  exec(editor: IDomEditor, value: string | boolean) {
  
    
    const node = {
      type: "japspace",
     
      children: [{ text: "\u3000" }],
    };
    editor?.insertNode(node);
    console.log(editor.getHtml());
  
  }

**Comment by cycleccc** [comment]
需要定义一个自定义元素及对应的解析函数，不然不合法的字符会被解析成其它元素或过滤 。
具体看文档 [自定义元素](https://cycleccc.github.io/docs/guide/development#%E5%AE%9A%E4%B9%89%E6%96%B0%E5%85%83%E7%B4%A0)
及其它现成的插件 demo
