### ISSUE TITLE
Bug: 表格单元格内多选内容删除事件没有执行

### ISSUE THREAD

**Issue by cycleccc** [wangeditor-next/wangEditor-next#319]
https://github.com/user-attachments/assets/72690c81-05d8-4996-ae6e-86b7f58c3de2

_Originally posted by @along521 in https://github.com/cycleccc/wangEditor-next/discussions/318#discussioncomment-11173744_

**Comment by xb1357686** [comment]
@cycleccc  能问下这个问题，是哪个版本引发的不？  我为了解决单元格输入有时候文字会错位，从5.5.4 更新到了5.6.8， 发现错位的问题解决了， 也发现了这个删除的问题

**Comment by cycleccc** [comment]
@xb1357686 应该是 5.6.8 解决这个问题引起的  https://github.com/cycleccc/wangEditor-next/issues/278
可以先降版本到 5.6.7 试试

**Comment by xb1357686** [comment]
@cycleccc 感谢老铁，点赞
