### ISSUE TITLE
markdown无法

### ISSUE THREAD

**Issue by quhongli123** [wangeditor-next/wangEditor-next#325]
## bug 描述

*markdown无法展示*

## 你预期的样子是？

*请输入内容……*

## 系统和浏览器及版本号

- 操作系统
- 浏览器和版本

## wangEditor-next 版本

*
[
<img width="346" alt="image" src="https://github.com/user-attachments/assets/71896521-7d2f-4217-95e7-efcd18e68bc8">
](url)
[
<img width="233" alt="image" src="https://github.com/user-attachments/assets/bf3c09cb-9f3f-444e-ad75-e118d477f4e0">
](url)
*

## demo 能否复现该 bug ？

能

- demo https://cycleccc.github.io/demo/

## 在线 demo

- 沙盒链接: https://stackblitz.com/@cycleccc/collections/wangeditor

## 最小成本的复现步骤

- 步骤一
- 步骤二
- 步骤三

**Comment by cycleccc** [comment]
我搞错了，没发布，现在 markdown 插件发布了https://www.npmjs.com/package/@wangeditor-next/plugin-markdown
用法相同。换一下包名和版本就行
