### ISSUE TITLE
Bug：第一行插入表格，无法全选删除（已在 wangEditor-next 实现）

### ISSUE THREAD

**Issue by cycleccc** [wangeditor-next/wangEditor-next#33]
相关 issue：
https://github.com/wangeditor-team/wangEditor/issues/5761
https://github.com/wangeditor-team/wangEditor/issues/5675

**Comment by cycleccc** [comment]
这个 bug 感觉不太好解决，现在的方案是 inserttable 时  特判如果table 是第一个children 就在前面插入一个 空 paragraph。

两害相权取其轻，后面再开一个 issue 详细描述为什么这个 bug 不好解决，有兴趣的小伙伴也可以来试试解决它。

**Comment by fanbinghuadev** [comment]
> 这个 bug 感觉不太好解决，现在的方案是 inserttable 时 特判如果table 是第一个children 就在前面插入一个 空 paragraph。
> 
> 两害相权取其轻，后面再开一个 issue 详细描述为什么这个 bug 不好解决，有兴趣的小伙伴也可以来试试解决它。

能重写 clear 方法吗？把 Transforms.delete 换成 Transforms.removeNodes  

因为 slatejs 官方对 Transforms.delete 的描述是： Delete text in the document ，应该只是删除文本节点，并没有删除表格、图片等节点

![Image](https://github.com/user-attachments/assets/9bd0a79c-a098-4690-bd90-a0a69d529737)

当前我们清空内容采用的是以下方式：

![Image](https://github.com/user-attachments/assets/b4148012-d77f-43ff-a378-514aec54851b)
