### ISSUE TITLE
bug 表格里加空格会导致样式丢失

### ISSUE THREAD

**Issue by along521** [wangeditor-next/wangEditor-next#334]
## bug 描述

表格里加空格会导致样式丢失

## 你预期的样子是？

正确的样式

## 系统和浏览器及版本号

- macos15
- 谷歌最新版

## wangEditor-next 版本

 "@wangeditor-next/editor": "^5.6.7",
   "@wangeditor-next/editor-for-vue2": "^1.0.2",

## demo 能否复现该 bug ？

能

## 最小成本的复现步骤
wps 中按照图片中的格式进行复制过去 会导致样式丢失，样式中间包含空格
<img width="1116" alt="image" src="https://github.com/user-attachments/assets/8894c8c9-c160-4c43-976a-ba126e573b78">

**Comment by cycleccc** [comment]
能上传一下复现的 wps 附件吗

**Comment by along521** [comment]
> 能上传一下复现的 wps 附件吗

[Uploading 复现问题.docx…]()

**Comment by along521** [comment]
> 能上传一下复现的 wps 附件吗

[复现问题.docx](https://github.com/user-attachments/files/17694790/default.docx)
