### ISSUE TITLE
Bug: v5.6.10 wps表格插入行报错

### ISSUE THREAD

**Issue by panxin226** [wangeditor-next/wangEditor-next#338]
## bug 描述
您好，最近发现有的表格插入行会报错，数据请见附件，demo示例可以复现。是不是在word里面操作表格，合并单元格之类的操作然后复制到编辑器里面就不行了？
表格插入行报错
![image](https://github.com/user-attachments/assets/d6a5b84f-d59a-458e-ad59-c30b460768e2)

*请输入内容……*

## 你预期的样子是？

*请输入内容……*
word里面的表格复制进来可用
## 系统和浏览器及版本号

- 操作系统
- 浏览器和版本

## wangEditor-next 版本

*请输入内容……*
最新版
## demo 能否复现该 bug ？

能/不能
能
- demo https://cycleccc.github.io/demo/

## 在线 demo

- 沙盒链接: https://stackblitz.com/@cycleccc/collections/wangeditor

## 最小成本的复现步骤

- 步骤一
<table style="width: auto;table-layout: fixed;height:123.1875"><colgroup contentEditable="false"><col width=180></col><col width=180></col><col width=180></col><col width=180></col></colgroup><tbody><tr><td colspan="4" rowspan="1" width="auto" style="border-width: 1px; border-style: solid; border-color: rgb(204, 204, 204);"><p><br></p></td></tr><tr><td colspan="1" rowspan="1" width="auto" style="border-width: 1px; border-style: solid; border-color: rgb(204, 204, 204);"><p><span style="font-size: 12pt; font-family: 宋体;"> </span></p></td><td colspan="1" rowspan="1" width="auto" style="border-width: 1px; border-style: solid; border-color: rgb(204, 204, 204);"><p><span style="font-size: 12pt; font-family: 宋体;"> </span></p></td><td colspan="1" rowspan="1" width="auto" style="border-width: 1px; border-style: solid; border-color: rgb(204, 204, 204);"><p><span style="font-size: 12pt; font-family: 宋体;"> </span></p></td><td colspan="1" rowspan="1" width="auto" style="border-width: 1px; border-style: solid; border-color: rgb(204, 204, 204);"><p><br></p></td></tr></tbody></table><p><br></p>
- 步骤二

[新文件 4.txt](https://github.com/user-attachments/files/17713029/4.txt)

- 步骤三
[保存.docx](https://github.com/user-attachments/files/17712187/default.docx)

**Comment by cycleccc** [comment]
是最新版吗以及是 Microsoft word 吗？
wps 试了似乎没有问题，新文件4附件使用setHtml也没有问题。

**Comment by panxin226** [comment]
> 是最新版吗以及是 Microsoft word 吗？ wps 试了似乎没有问题，新文件4附件使用setHtml也没有问题。

就是wps 有问题，我在官网示例setHtml，表格可以呈现，但是插入行就会报错，详情请见视频如下： 
[屏幕录制 2024-11-12 161857.zip](https://github.com/user-attachments/files/17713313/2024-11-12.161857.zip)

**Comment by cycleccc** [comment]
最近比较忙，可能过两天或周末解决这个问题，急得话可以尝试降版本。
根本原因的话还是缺少针对 Microsoft Word 及 WPS 表格的各项测试，未来一段时间会暂停新功能的开发，补齐对应的测试。

**Comment by panxin226** [comment]
> 最近比较忙，可能过两天或周末解决这个问题，急得话可以尝试降版本。 根本原因的话还是缺少针对 Microsoft Word 及 WPS 表格的各项测试，未来一段时间会暂停新功能的开发，补齐对应的测试。

好的，感谢！
