### ISSUE TITLE
bug：复制粘贴飞书文档内容 渲染空格  多余的有序列表（已在 wangEditor-next 实现）

### ISSUE THREAD

**Issue by zhanShiChang** [wangeditor-next/wangEditor-next#34]
相关内容链接： https://ax3o9fzbjlt.feishu.cn/docx/ZmWDd9M7conImuxSN7mc0rPgnvh
复制到 [wangeditor-next](https://github.com/cycleccc/wangEditor-next) 即可复现

**Comment by cycleccc** [comment]
https://github.com/user-attachments/assets/34957881-8389-4a67-9804-4f1641e8165d

list 的问题解决了，code 标签现在是用于占整行的代码块，没用在文本标签上,这个更贴近于 Markdown 的使用了，这个另提 issue ，后面再看。
