### ISSUE TITLE
bug wps复制进来的数据表格中的样式丢失

### ISSUE THREAD

**Issue by along521** [wangeditor-next/wangEditor-next#342]
## bug 描述

 wps复制进来的数据表格中的样式丢失

## 你预期的样子是？

正确保留样式

## 系统和浏览器及版本号

- 操作系统
- 浏览器和版本

## wangEditor-next 版本

@wangeditor-next/editor@5.6.10

## demo 能否复现该 bug ？

能

<img width="720" alt="image" src="https://github.com/user-attachments/assets/76192872-da55-40bb-bf37-c9da7dd3fb34">

## 最小成本的复现步骤

把文档中文字复制进demo直接复现

[测试 空格.docx](https://github.com/user-attachments/files/17729416/default.docx)

**Comment by cycleccc** [comment]
和 #334 相同，已经修复了，发布了 wangeditor-next/core 补丁，可以更新依赖或是等发布 editor v5.6.11

**Comment by along521** [comment]
> 和 #334 相同，已经修复了，发布了 wangeditor-next/core 补丁，可以更新依赖或是等发布 editor v5.6.11

经测试，复制的表格内容无法删除了 选中和不选中 都无法删除

**Comment by cycleccc** [comment]
表格坑太多了，等修复这个bug后得完善单测了。

**Comment by along521** [comment]
> 表格坑太多了，等修复这个bug后得完善单测了。

先别堆功能了，把现有bug修复一下吧。
