### ISSUE TITLE
Bug: 5.6.14 版本配置默认字体和默认字号不生效

### ISSUE THREAD

**Issue by DejaVuuuuuuu** [wangeditor-next/wangEditor-next#348]
## bug 描述

*请输入内容……*

## 你预期的样子是？

*请输入内容……*

## 系统和浏览器及版本号

- 操作系统
- 浏览器和版本

## wangEditor-next 版本

*请输入内容……*

## demo 能否复现该 bug ？

能/不能

-[ demo https://cycleccc.github.io/demo/](https://stackblitz.com/edit/vue3-wangeditor-demo-patlkn?file=package.json,src%2Fcomponents%2FBasicEditor.vue)

demo里面可以复现这个问题

## 在线 demo

- 沙盒链接: https://stackblitz.com/edit/vue3-wangeditor-demo-qum4fm?file=src%2Fcomponents%2FBasicEditor.vue,src%2FApp.vue

## 最小成本的复现步骤
配置了默认字体不生效，不知道是不是我配置没写对

- 步骤一
- 步骤二
- 步骤三

**Comment by cycleccc** [comment]
https://stackblitz.com/edit/vue3-wangeditor-demo-krwhbb?file=src%2Fcomponents%2FBasicEditor.vue,src%2FApp.vue
比较这个 demo 看看

**Comment by DejaVuuuuuuu** [comment]
我沙盒链接有示例 我这个没有生效  我是写在setup里面的， 你这个示例是选项是的api  跟这个有关系吗

**Comment by cycleccc** [comment]
这是我把 demo 代码粘到你的沙盒链接里改的，跟 setup肯定没关系，看看哪里写法有问题。

**Comment by DejaVuuuuuuu** [comment]
https://stackblitz.com/edit/vue3-wangeditor-demo-qum4fm?file=src%2Fcomponents%2FBasicEditor.vue,src%2FApp.vue
我吧demo改成选项是的api就生效了。。。

**Comment by DejaVuuuuuuu** [comment]
![image](https://github.com/user-attachments/assets/65193296-cdb7-4434-9cb5-7bc86e085ddc)
https://stackblitz.com/edit/vue3-wangeditor-demo-patlkn?file=package.json,src%2Fcomponents%2FBasicEditor.vue
再这个demo里面有这个提示

**Comment by cycleccc** [comment]
和 vue3 setup 生命周期有关吧，vue3 具体生命周期使用有点忘了，你方便研究一下不

**Comment by DejaVuuuuuuu** [comment]
我试试吧

**Comment by DejaVuuuuuuu** [comment]
这个报错提示指的是没有在setup进行实例创建时没有发现这个属性，Vue官方报错告诉你可能是没有定义的原因。其他的属性都没有这个提示，应该还是组件内部的问题。

**Comment by cycleccc** [comment]
那可能要修改一下 [editor-for-vue](https://github.com/cycleccc/wangEditor-for-vue3) 包了，有兴趣的话可以修复看看，或是等我最近有空修复。

**Comment by DejaVuuuuuuu** [comment]
那就等大佬解决了麻烦告知一声
