### ISSUE TITLE
mui的Dialog组件内嵌Editor时，第二次显示Dialog引发的报错

### ISSUE THREAD

**Issue by qiweiff** [wangeditor-next/wangEditor-next#349]
## bug 描述

使用mui 6.1.6库的Dialog组件内嵌Editor，第一次显示(open)一切正常，第二次报错Error: Repeated create toolbar by selector '[object HTMLDivElement]'
我发现很多和我有相同情况的开发者，但并没有发现解决方案，如果有人能解决问题，希望可以回复我

## 你预期的样子是？

不报错正常显示

## 系统和浏览器及版本号

- w11
- edge

## wangEditor-next 版本

    "@wangeditor-next/editor": "^5.6.12",
    "@wangeditor-next/editor-for-react": "^1.0.8",

## demo 能否复现该 bug ？

能

- demo https://stackblitz.com/edit/react-a9pbrj?file=src%2Findex.js

## 在线 demo

- 沙盒链接: https://stackblitz.com/edit/react-a9pbrj?file=src%2Findex.js

## 最小成本的复现步骤

一、使用mui库的Dialog组件包裹Editor和Toolbar
二、使用按钮显示Dialog组件，然后关闭Dialog、再开启

**Comment by cycleccc** [comment]
已在 editor-for-react 1.0.9 版本解决
