### ISSUE TITLE
多次点击回车后再点击删除按钮无法回到第一行

### ISSUE THREAD

**Issue by zxzf1234** [wangeditor-next/wangEditor-next#358]
## bug 描述

多次点击回车后再点击删除按钮无法回到第一行

## 你预期的样子是？

多次点击回车后再点击删除按钮可以回到第一行

## 系统和浏览器及版本号

- win11
- chrome 130.0.6723.119

## wangEditor-next 版本

"@wangeditor-next/editor": "^5.6.13",
    "@wangeditor-next/editor-for-vue": "^5.1.14",

## demo 能否复现该 bug ？

能

- demo https://cycleccc.github.io/demo/

## 最小成本的复现步骤

- 步骤一 多次点击回车
- 步骤二 再点击删除按钮

**Comment by cycleccc** [comment]
感谢反馈，和一个优化点有关，后续发现有一定问题，已经回滚了，请升级到大于 5.6.13 的版本。
