### ISSUE TITLE
@wangeditor-next/plugin-formula katex.css没有默认导出

### ISSUE THREAD

**Issue by dexterBo** [wangeditor-next/wangEditor-next#361]
## 问题描述

vue3使用@wangeditor-next/plugin-formula插件
Unexpected error when starting the router: SyntaxError: The requested module '/node_modules/katex/dist/katex.css' does not provide an export named 'default' (at @wangeditor-next_plugin-formula.js?v=51435bc8:16:8)

## wangEditor 版本

 "@wangeditor-next/editor": "^5.6.14",
  "@wangeditor-next/editor-for-vue": "^5.1.14",
  "@wangeditor-next/plugin-formula": "^0.0.7",
   "katex": "^0.16.11",

## 是否查阅了文档 ？

是

## 最小成本的复现步骤

<img width="514" alt="image" src="https://github.com/user-attachments/assets/9e48b6fe-c763-4227-baad-f39906588feb">
<img width="1238" alt="image" src="https://github.com/user-attachments/assets/463a238c-4abc-4202-aa78-33f6179f2d3e">

- 步骤一
- npm create vue@latest 新建一个vue3项目
- 步骤二
-  添加katex依赖
- 步骤三
- 在main.ts里添加import katexStyleContent from 'katex/dist/katex.css'

**Comment by cycleccc** [comment]
方便用下面这个 demo 复现一下吗
https://stackblitz.com/edit/vue3-wangeditor-demo-ovcoub?file=package.json,src%2Fcomponents%2FBasicEditor.vue

**Comment by dexterBo** [comment]
我用线上的没有复现，但是在本地创建的新vue项目会有这个问题。

**Comment by dexterBo** [comment]
https://codesandbox.io/p/devbox/old-sun-mpv3d3?workspaceId=e557ac7b-c758-4d48-91be-442a78898666
在这里复现了。

**Comment by cycleccc** [comment]
https://codesandbox.io/p/devbox/suspicious-lewin-sh6xn5?file=%2Fsrc%2Fcomponents%2FBasicEditor.vue
看下这个，Markdown 和 formula 插件都能使用

**Comment by dexterBo** [comment]
https://codesandbox.io/p/devbox/suspicious-lewin-sh6xn5?file=%2Fsrc%2Fcomponents%2FBasicEditor.vue
 看下这个，Markdown 和 formula 插件都能使用
![image](https://github.com/user-attachments/assets/3235f55e-c0f0-44f4-8776-916e74e277cc)


并不行呀，一样会有这个问题。

**Comment by cycleccc** [comment]
升级到 0.0.10 试试
https://codesandbox.io/p/devbox/suspicious-lewin-sh6xn5?file=%2Fsrc%2Fstyle.css%3A65%2C28
