### ISSUE TITLE
复制粘贴进来的内容太长了，会卡顿，长时间无响应

### ISSUE THREAD

**Issue by zhengzhishu** [wangeditor-next/wangEditor-next#364]
## bug 描述

*复制粘贴进来的内容长了之后，会反应很久，或者直接无响应*

## 你预期的样子是？

*能粘贴就显示*

## 系统和浏览器及版本号

- 操作系统
- 浏览器和版本

## wangEditor-next 版本

*请输入内容……*

## demo 能否复现该 bug ？

能/不能

- demo https://cycleccc.github.io/demo/

## 在线 demo

- 沙盒链接: https://stackblitz.com/@cycleccc/collections/wangeditor

## 最小成本的复现步骤

- 步骤一
- 步骤二
- 步骤三

**Comment by cycleccc** [comment]
是否是太多表格数据，如这个 issue https://github.com/cycleccc/wangEditor-next/issues/309

**Comment by zhengzhishu** [comment]
是的，里面大概有四五个表格数据，一共是大概10页的word文档，然后用户复制粘贴进去，要么长时间未响应，要么很久才出现&nbsp;


黑炭
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年11月20日(星期三) 下午3:24
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [cycleccc/wangEditor-next] 复制粘贴进来的内容太长了，会卡顿，长时间无响应 (Issue #364)














 
是否是太多表格数据，如这个 issue #309

**Comment by cycleccc** [comment]
暂时先尝试分页吧，复制的内容太多时分段分页展示。现在渲染的逻辑太多，不好处理。

**Comment by cycleccc** [comment]
重复内容，在 #309 讨论。
