### ISSUE TITLE
正常注册后报错

### ISSUE THREAD

**Issue by Zzhangzewu** [wangeditor-next/wangEditor-next#367]
## bug 描述

*请输入内容……*
import MarkdownPlugin from '@wangeditor-next/plugin-markdown'
Boot.registerModule(MarkdownPlugin)

正常注册后报错

 error  in ./node_modules/@wangeditor-next/plugin-markdown/dist/index.mjs

Can't import the named export 'DomEditor' from non EcmaScript module (only default export is available)

 error  in ./node_modules/@wangeditor-next/plugin-markdown/dist/index.mjs

Can't import the named export 'SlateEditor' from non EcmaScript module (only default export is available)

 error  in ./node_modules/@wangeditor-next/plugin-markdown/dist/index.mjs

Can't import the named export 'SlateRange' from non EcmaScript module (only default export is available)

 error  in ./node_modules/@wangeditor-next/plugin-markdown/dist/index.mjs

Can't import the named export 'SlateTransforms' from non EcmaScript module (only default export is available)

## wangEditor-next 版本
 "@wangeditor-next/editor": "^5.6.14",
 "@wangeditor-next/editor-for-vue2": "^1.0.2",
 "@wangeditor-next/plugin-markdown": "^0.0.6",

**Comment by cycleccc** [comment]
这个错误是兜底错误，比较模糊，方便出个 demo 吗 用在线沙盒复现一下

**Comment by cycleccc** [comment]
https://codesandbox.io/p/devbox/suspicious-lewin-sh6xn5?file=%2Fsrc%2Fcomponents%2FBasicEditor.vue
这里是一个 vue3 的沙盒demo 你可以照着复现下 vue2 的看看有没有问题。

**Comment by Zzhangzewu** [comment]
> https://codesandbox.io/p/devbox/suspicious-lewin-sh6xn5?file=%2Fsrc%2Fcomponents%2FBasicEditor.vue 这里是一个 vue3 的沙盒demo 你可以照着复现下 vue2 的看看有没有问题。

已解决该问题

**Comment by boe1900** [comment]
> > https://codesandbox.io/p/devbox/suspicious-lewin-sh6xn5?file=%2Fsrc%2Fcomponents%2FBasicEditor.vue 这里是一个 vue3 的沙盒demo 你可以照着复现下 vue2 的看看有没有问题。
> 
> 已解决该问题

我也遇到了跟你一样的问题，请问你是如何解决的？
