### ISSUE TITLE
拿到html后，表格样式丢失，表格表头无样式

### ISSUE THREAD

**Issue by Chendamao** [wangeditor-next/wangEditor-next#374]
![image](https://github.com/user-attachments/assets/b8ee99e9-48c9-406b-8df0-dd9f01e3ac35)
![image](https://github.com/user-attachments/assets/f0cdeb20-014d-4811-83bd-e093093f9c46)

表头样式丢失，而且下面两行空表格也被折叠了

**Comment by cycleccc** [comment]
麻烦把复现的附件上传一下

**Comment by cycleccc** [comment]
可能是样式冲突了，等后面再遇到相同的问题，贴上 对应的 html 再看看吧

**Comment by Chendamao** [comment]
这是拿到的THTML：<p><br></p><table style=\"width: auto;table-layout: fixed;height:168\"><colgroup contentEditable=\"false\"><col width=60></col><col width=60></col><col width=62></col><col width=60></col><col width=60></col><col width=60></col></colgroup><tbody><tr><th colSpan=\"1\" rowSpan=\"1\" width=\"auto\" style=\"\"></th><th colSpan=\"1\" rowSpan=\"1\" width=\"auto\" style=\"\"></th><th colSpan=\"1\" rowSpan=\"1\" width=\"auto\" style=\"\"></th><th colSpan=\"1\" rowSpan=\"1\" width=\"auto\" style=\"\"></th><th colSpan=\"1\" rowSpan=\"1\" width=\"auto\" style=\"\"></th><th colSpan=\"1\" rowSpan=\"1\" width=\"auto\" style=\"\"></th></tr><tr><td colspan=\"1\" rowspan=\"1\" width=\"auto\" style=\"border-width: 1px; border-style: solid; border-color: rgb(204, 204, 204);\"></td><td colspan=\"1\" rowspan=\"1\" width=\"auto\" style=\"border-width: 1px; border-style: solid; border-color: rgb(204, 204, 204);\"></td><td colspan=\"1\" rowspan=\"1\" width=\"auto\" style=\"border-width: 1px; border-style: solid; border-color: rgb(204, 204, 204);\"></td><td colspan=\"1\" rowspan=\"1\" width=\"auto\" style=\"border-width: 1px; border-style: solid; border-color: rgb(204, 204, 204);\"></td><td colspan=\"1\" rowspan=\"1\" width=\"auto\" style=\"border-width: 1px; border-style: solid; border-color: rgb(204, 204, 204);\"></td><td colspan=\"1\" rowspan=\"1\" width=\"auto\" style=\"border-width: 1px; border-style: solid; border-color: rgb(204, 204, 204);\"></td></tr><tr><td colspan=\"1\" rowspan=\"1\" width=\"auto\" style=\"border-width: 1px; border-style: solid; border-color: rgb(204, 204, 204);\"></td><td colspan=\"1\" rowspan=\"1\" width=\"auto\" style=\"border-width: 1px; border-style: solid; border-color: rgb(204, 204, 204);\"></td><td colspan=\"1\" rowspan=\"1\" width=\"auto\" style=\"border-width: 1px; border-style: solid; border-color: rgb(204, 204, 204);\"><span style=\"color: rgba(0, 0, 0, 0.85); font-size: 14px;\"> </span></td><td colspan=\"1\" rowspan=\"1\" width=\"auto\" style=\"border-width: 1px; border-style: solid; border-color: rgb(204, 204, 204);\"></td><td colspan=\"1\" rowspan=\"1\" width=\"auto\" style=\"border-width: 1px; border-style: solid; border-color: rgb(204, 204, 204);\"></td><td colspan=\"1\" rowspan=\"1\" width=\"auto\" style=\"border-width: 1px; border-style: solid; border-color: rgb(204, 204, 204);\"></td></tr><tr><td colspan=\"1\" rowspan=\"1\" width=\"auto\" style=\"border-width: 1px; border-style: solid; border-color: rgb(204, 204, 204);\"></td><td colspan=\"1\" rowspan=\"1\" width=\"auto\" style=\"border-width: 1px; border-style: solid; border-color: rgb(204, 204, 204);\"></td><td colspan=\"1\" rowspan=\"1\" width=\"auto\" style=\"border-width: 1px; border-style: solid; border-color: rgb(204, 204, 204);\"></td><td colspan=\"1\" rowspan=\"1\" width=\"auto\" style=\"border-width: 1px; border-style: solid; border-color: rgb(204, 204, 204);\"></td><td colspan=\"1\" rowspan=\"1\" width=\"auto\" style=\"border-width: 1px; border-style: solid; border-color: rgb(204, 204, 204);\"></td><td colspan=\"1\" rowspan=\"1\" width=\"auto\" style=\"border-width: 1px; border-style: solid; border-color: rgb(204, 204, 204);\"></td></tr><tr><td colspan=\"1\" rowspan=\"1\" width=\"auto\" style=\"border-width: 1px; border-style: solid; border-color: rgb(204, 204, 204);\"></td><td colspan=\"1\" rowspan=\"1\" width=\"auto\" style=\"border-width: 1px; border-style: solid; border-color: rgb(204, 204, 204);\"></td><td colspan=\"1\" rowspan=\"1\" width=\"auto\" style=\"border-width: 1px; border-style: solid; border-color: rgb(204, 204, 204);\"></td><td colspan=\"1\" rowspan=\"1\" width=\"auto\" style=\"border-width: 1px; border-style: solid; border-color: rgb(204, 204, 204);\"></td><td colspan=\"1\" rowspan=\"1\" width=\"auto\" style=\"border-width: 1px; border-style: solid; border-color: rgb(204, 204, 204);\"></td><td colspan=\"1\" rowspan=\"1\" width=\"auto\" style=\"border-width: 1px; border-style: solid; border-color: rgb(204, 204, 204);\"></td></tr><tr><td colspan=\"1\" rowspan=\"1\" width=\"auto\" style=\"border-width: 1px; border-style: solid; border-color: rgb(204, 204, 204);\"></td><td colspan=\"1\" rowspan=\"1\" width=\"auto\" style=\"border-width: 1px; border-style: solid; border-color: rgb(204, 204, 204);\"></td><td colspan=\"1\" rowspan=\"1\" width=\"auto\" style=\"border-width: 1px; border-style: solid; border-color: rgb(204, 204, 204);\"></td><td colspan=\"1\" rowspan=\"1\" width=\"auto\" style=\"border-width: 1px; border-style: solid; border-color: rgb(204, 204, 204);\"></td><td colspan=\"1\" rowspan=\"1\" width=\"auto\" style=\"border-width: 1px; border-style: solid; border-color: rgb(204, 204, 204);\"></td><td colspan=\"1\" rowspan=\"1\" width=\"auto\" style=\"border-width: 1px; border-style: solid; border-color: rgb(204, 204, 204);\"></td></tr></tbody></table><p><br></p>


通过v-html展示在页面上，显示如下：
![image](https://github.com/user-attachments/assets/d6a86994-b28f-421a-bcf3-1886a9aec0c7)
实际的样式应该是如下样式：
![image](https://github.com/user-attachments/assets/344305f1-dd99-46c5-8e2e-8ff36755f0b5)

**Comment by cycleccc** [comment]
这个 html 是通过 wangeditor 得到的吗，格式看着有点奇怪，方便录下屏看看是怎么获取的这个对应的 html 的吗？
