### ISSUE TITLE
复制excel数据到编辑器中格式错乱

### ISSUE THREAD

**Issue by 1295385531** [wangeditor-next/wangEditor-next#375]
复制excel数据到编辑器中格式错乱
在旧版的demo中去粘贴是正常的：https://www.wangeditor.com/demo/index.html 这个demo
在https://cycleccc.github.io/demo/ demo中去粘贴就是错乱的
参考视频：
https://github.com/user-attachments/assets/214fa5b3-1983-4853-abea-0e6388b4afdf

**Comment by cycleccc** [comment]
麻烦把复现的附件上传一下

**Comment by 1295385531** [comment]
https://github.com/user-attachments/assets/d9d91506-b8a5-4802-bb52-42236d06294b

**Comment by 1295385531** [comment]
[h5开票.xlsx](https://github.com/user-attachments/files/17840747/h5.xlsx)

**Comment by xb1357686** [comment]
我这边用户复制过来的表格，还出现过右下角最后一个单元格的dom节点都不存在，只是table有边框，看着像是个完整的表格，光标过不去，嘿嘿
