### ISSUE TITLE
一段富文本赋值后，富文本编辑器会被禁用

### ISSUE THREAD

**Issue by dsaw111** [wangeditor-next/wangEditor-next#380]
## bug 描述

`const txt = '<p><span style="display: inline !important;"><img src="http://gips2.baidu.com/it/u=195724436,3554684702&fm=3028&app=3028&f=JPEG&fmt=auto?w=1280&h=960" style="max-width:100%;"><br></span></p>';
try {
    editor.setHtml(txt);
} catch (error) {}`

以上代码执行后，富文本编辑器内为空，并且编辑器进入禁用状态，但是editor.isDisabled()返回false

## 你预期的样子是？

富文本编辑器不要禁用

## 系统和浏览器及版本号

- 操作系统 Windows 10 企业版 22H2
- 浏览器和版本 Google Chrome 131.0.6778.86（正式版本） （64 位）

## wangEditor-next 版本

"@wangeditor-next/editor": "^5.6.6",

**Comment by cycleccc** [comment]
格式问题，解析错误了，img外层的span标签和div标签需要去掉。这是常见的问题，后续会写到文档里。
相关 discussions https://github.com/cycleccc/wangEditor-next/discussions/370

**Comment by cycleccc** [comment]
改成如以下格式
```html
<p><img src="http://gips2.baidu.com/it/u=195724436,3554684702&fm=3028&app=3028&f=JPEG&fmt=auto?w=1280&h=960" style="max-width:100%;"></p>
```
或是
```html
<img src="http://gips2.baidu.com/it/u=195724436,3554684702&fm=3028&app=3028&f=JPEG&fmt=auto?w=1280&h=960" style="max-width:100%;">
```
