### ISSUE TITLE
table表格无法合并

### ISSUE THREAD

**Issue by xiaolu2233** [wangeditor-next/wangEditor-next#385]
## bug 描述

初始化createEditor时设置的html模板中的表格可以显示到富文本但无法合并单元格、新增或删除行

## 你预期的样子是？

可以合并、添加、删除单元格

## 系统和浏览器及版本号

- 操作系统
- win11
- 浏览器和版本
- 谷歌 版本 122.0.6261.129（正式版本） （64 位）

## wangEditor-next 版本

*请输入内容……*

## demo 能否复现该 bug ？

能

- demo https://cycleccc.github.io/demo/

## 在线 demo

- 沙盒链接: https://stackblitz.com/@cycleccc/collections/wangeditor

## 最小成本的复现步骤

- 步骤一
- 打开[https://cycleccc.github.io/demo/set-html.html 选择设置 HTML]()](https://cycleccc.github.io/demo/set-html.html)
- 步骤二
- 复制模板到输入框
-  <p><br></p>
          <table style="width: auto;table-layout: fixed;height:504.796875">
            <colgroup contentEditable="false">
              <col width=60></col>
              <col width=120></col>
              <col width=86></col>
              <col width=746></col>
              <col width=86></col>
            </colgroup>
          <tbody>
            <tr>
              <th colSpan="4" rowSpan="1" width="auto" style="">月度绩效评估结果：（根据各岗位工作职责，量化说明绩效目标与结果） </th>
              <th colSpan="3" rowSpan="1" width="auto" style=""></th>
              <th colSpan="1" rowSpan="1" width="auto" style=""></th>
              <th colSpan="1" rowSpan="1" width="auto" style=""></th>
              <th colSpan="1" rowSpan="2" width="auto" style="">绩效分</th>
            </tr>
            <tr>
              <td colSpan="1" rowSpan="1" width="auto" style=""><strong>序号</strong></td>
              <td colSpan="1" rowSpan="1" width="auto" style=""><strong>考核内容</strong></td>
              <td colSpan="1" rowSpan="1" width="auto" style=""><strong>基准分</strong></td>
              <td colSpan="1" rowSpan="1" width="auto" style=""><strong>考核标准</strong></td>
              <td colSpan="1" rowSpan="1" width="auto" style=""></td>
            </tr>
            <tr>
              <td colSpan="1" rowSpan="1" width="auto" style="">1</td>
              <td colSpan="1" rowSpan="1" width="auto" style="">话务量</td>
              <td colSpan="1" rowSpan="1" width="auto" style=""></td>
              <td colSpan="1" rowSpan="1" width="auto" style="">根据月度话务量服务分核算</td>
              <td colSpan="1" rowSpan="1" width="auto" style=""></td>
            </tr>
            <tr>
              <td colSpan="1" rowSpan="1" width="auto" style="">2</td>
              <td colSpan="1" rowSpan="1" width="auto" style="">企微有效服务<br><br></td>
              <td colSpan="1" rowSpan="1" width="auto" style=""></td>
              <td colSpan="1" rowSpan="1" width="auto" style="">根据月度企微有效服务得分核算</td>
              <td colSpan="1" rowSpan="1" width="auto" style=""></td>
            </tr>
            <tr>
              <td colSpan="1" rowSpan="1" width="auto" style="">3</td>
              <td colSpan="1" rowSpan="1" width="auto" style="">转化有效户净收入</td>
              <td colSpan="1" rowSpan="1" width="auto" style=""></td>
              <td colSpan="1" rowSpan="1" width="auto" style="">根据转化有效户净收入营销分核算</td>
              <td colSpan="1" rowSpan="1" width="auto" style=""></td>
            </tr>
            <tr>
              <td colSpan="1" rowSpan="1" width="auto" style="">4</td>
              <td colSpan="1" rowSpan="1" width="auto" style="">运营策划</td>
              <td colSpan="1" rowSpan="1" width="auto" style=""></td>
              <td colSpan="1" rowSpan="1" width="auto" style="">策划方案（企微运营方案、活动策划方案、APP促活方案、直播、短视频脚本等）被采纳，5分/方案；参与短视频拍摄，5分/次；担任主播、助播，10分/次；上限50分/月</td>
              <td colSpan="1" rowSpan="1" width="auto" style=""></td>
            </tr>
            <tr>
              <td colSpan="1" rowSpan="1" width="auto" style="">5</td>
              <td colSpan="1" rowSpan="1" width="auto" style="">线上有效服务覆盖 <br><br></td>
              <td colSpan="1" rowSpan="1" width="auto" style=""></td>
              <td colSpan="1" rowSpan="1" width="auto" style="">覆盖率得分=（当月线上有效服务覆盖率-25%）×100×10，0分封底，当月添加企微客户数小于50户则不计算该得分，上限80分/月</td><td colSpan="1" rowSpan="1" width="auto" style=""></td>
            </tr>
            <tr>
              <td colSpan="1" rowSpan="1" width="auto" style="">6</td>
              <td colSpan="1" rowSpan="1" width="auto" style="">有效率提升得分</td>
              <td colSpan="1" rowSpan="1" width="auto" style=""></td>
              <td colSpan="1" rowSpan="1" width="auto" style="">（当月月末有效户率-上月月末有效户率）×100×50，0分封底</td>
              <td colSpan="1" rowSpan="1" width="auto" style=""></td>
            </tr>
            <tr>
              <td colSpan="1" rowSpan="1" width="auto" style="">7</td>
              <td colSpan="1" rowSpan="1" width="auto" style="">有效率占比得分</td>
              <td colSpan="1" rowSpan="1" width="auto" style=""></td>
              <td colSpan="1" rowSpan="1" width="auto" style="">	<br>（期末有效户率/第一名有效户率-40%）×100×5，0分封底</td>
              <td colSpan="1" rowSpan="1" width="auto" style=""></td>
            </tr>
            <tr>
              <td colSpan="1" rowSpan="1" width="auto" style="">8</td>
              <td colSpan="1" rowSpan="1" width="auto" style=""> 失效户率扣分</td>
              <td colSpan="1" rowSpan="1" width="auto" style=""></td>
              <td colSpan="1" rowSpan="1" width="auto" style="">（60%-期末失效户率/最后一名失效户率）×100，0分封顶，-20分封底</td><td colSpan="1" rowSpan="1" width="auto" style=""></td>
            </tr>
            <tr>
              <td colSpan="1" rowSpan="1" width="auto" style="">9</td>
              <td colSpan="1" rowSpan="1" width="auto" style="">日常工作综合评价</td><td colSpan="1" rowSpan="1" width="auto" style=""></td>
              <td colSpan="1" rowSpan="1" width="auto" style="">-20—20分 </td>
              <td colSpan="1" rowSpan="1" width="auto" style=""></td>
            </tr>
            <tr>
              <td colSpan="4" rowSpan="1" width="auto" style=""><strong>合计分</strong></td>
              <td colSpan="1" rowSpan="1" width="auto" style=""></td>
              <td colSpan="1" rowSpan="1" width="auto" style=""></td>
              <td colSpan="1" rowSpan="1" width="auto" style=""></td>
              <td colSpan="1" rowSpan="1" width="auto" style=""></td>
            </tr>
            <tr>
              <td colSpan="5" rowSpan="1" width="auto" style=""><strong>月度部门内或跨部门协助工作、分公司各岗位业务流程改进建议、知识要点库更新 </strong></td>
              <td colSpan="1" rowSpan="1" width="auto" style=""></td>
              <td colSpan="1" rowSpan="1" width="auto" style=""></td>
              <td colSpan="1" rowSpan="1" width="auto" style=""></td>
              <td colSpan="1" rowSpan="1" width="auto" style=""></td>
            </tr>
            <tr>
              <td colSpan="1" rowSpan="1" width="auto" style=""><strong>序号</strong></td>
              <td colSpan="3" rowSpan="1" width="auto" style=""><strong>具体事项说明</strong></td>
              <td colSpan="1" rowSpan="1" width="auto" style=""></td>
              <td colSpan="1" rowSpan="1" width="auto" style=""></td>
              <td colSpan="1" rowSpan="1" width="auto" style=""><strong>员工自评分</strong></td>
            </tr>
            <tr>
              <td colSpan="1" rowSpan="1" width="auto" style="">1</td>
              <td colSpan="3" rowSpan="1" width="auto" style=""></td>
              <td colSpan="1" rowSpan="1" width="auto" style=""></td>
              <td colSpan="1" rowSpan="1" width="auto" style=""></td>
              <td colSpan="1" rowSpan="1" width="auto" style=""></td>
            </tr>
            <tr>
              <td colSpan="1" rowSpan="1" width="auto" style="">2</td>
              <td colSpan="3" rowSpan="1" width="auto" style=""></td>
              <td colSpan="1" rowSpan="1" width="auto" style=""></td>
              <td colSpan="1" rowSpan="1" width="auto" style=""></td>
              <td colSpan="1" rowSpan="1" width="auto" style=""></td>
            </tr>
            <tr>
              <td colSpan="1" rowSpan="1" width="auto" style=""></td>
              <td colSpan="1" rowSpan="1" width="auto" style=""></td>
              <td colSpan="1" rowSpan="1" width="auto" style=""></td>
              <td colSpan="1" rowSpan="1" width="auto" style=""></td>
              <td colSpan="1" rowSpan="1" width="auto" style=""></td>
            </tr>
            <tr>
              <td colSpan="1" rowSpan="1" width="auto" style=""></td>
              <td colSpan="1" rowSpan="1" width="auto" style=""></td>
              <td colSpan="1" rowSpan="1" width="auto" style=""></td>
              <td colSpan="1" rowSpan="1" width="auto" style=""></td>
              <td colSpan="1" rowSpan="1" width="auto" style=""></td>
            </tr>
            <tr>
              <td colSpan="1" rowSpan="1" width="auto" style=""></td>
              <td colSpan="1" rowSpan="1" width="auto" style=""></td>
              <td colSpan="1" rowSpan="1" width="auto" style=""></td>
              <td colSpan="1" rowSpan="1" width="auto" style=""></td>
              <td colSpan="1" rowSpan="1" width="auto" style=""></td>
            </tr>
            <tr>
              <td colSpan="1" rowSpan="1" width="auto" style=""></td>
              <td colSpan="1" rowSpan="1" width="auto" style=""></td>
              <td colSpan="1" rowSpan="1" width="auto" style=""></td>
              <td colSpan="1" rowSpan="1" width="auto" style=""></td>
              <td colSpan="1" rowSpan="1" width="auto" style=""></td>
            </tr>
            <tr>
              <td colSpan="1" rowSpan="1" width="auto" style=""></td>
              <td colSpan="1" rowSpan="1" width="auto" style=""></td>
              <td colSpan="1" rowSpan="1" width="auto" style=""></td>
              <td colSpan="1" rowSpan="1" width="auto" style=""></td>
              <td colSpan="1" rowSpan="1" width="auto" style=""></td>
            </tr>
          </tbody>
        </table>
        <p><br></p>
- 步骤三
- 随便选中单元格合并 会有报错
-  Uncaught TypeError: undefined is not iterable (cannot read property Symbol(Symbol.iterator))

**Comment by cycleccc** [comment]
这段html表格是 wangeditor 内设置的不，看起来html格式有问题。

![image](https://github.com/user-attachments/assets/45144a40-4dd7-4684-b2f2-b366222fe708)
