### ISSUE TITLE
自定义粘贴，文本如果包含换行符，在富文本编辑器中文字就无法设置颜色

### ISSUE THREAD

**Issue by dsaw111** [wangeditor-next/wangEditor-next#387]
## bug 描述

自定义粘贴功能，如果复制过来的文本包含换行符，文字就无法设置颜色

`
      customPaste: (editor: IDomEditor, event: ClipboardEvent): boolean => {
        const text = event.clipboardData?.getData('text/plain');
        text && editor.insertText(text);  //text的值为'信息认证\r\n管理\r\n作者'
        event.preventDefault()
        return false;
      },
`

## 你预期的样子是？

文字可以设置颜色

## 系统和浏览器及版本号

操作系统 Windows 10 企业版 22H2
浏览器和版本 Google Chrome 131.0.6778.86（正式版本） （64 位）

## wangEditor-next 版本

"@wangeditor-next/editor": "^5.6.6",

**Comment by cycleccc** [comment]
方便出一份对应的复现吗

**Comment by dsaw111** [comment]
破案了，是因为富文本作为Form.Item，富文本onChange会把数据传给父节点，然后引起富文本的重复设置设置值

**Comment by cycleccc** [comment]
和 wangEditor 有关吗，没有关系的话 issue 就关闭了。
