### ISSUE TITLE
使用公式demo的时候出现了双份

### ISSUE THREAD

**Issue by LeonsCd** [wangeditor-next/wangEditor-next#390]
## 问题描述
调研阶段，因为我们对这个公式是刚需，所以用
@wangeditor-next/plugin-formula
在线实现了一下公式，还是挺惊喜的，但是在多个在线编辑器上使用，输入latex的时候，渲染出来的就双份的，很奇怪，按理说不应该，
我实在是找不到原因了，特此来请教一二，如有打扰，还请谅解，也有可能我有漏看
### 地址
https://stackblitz.com/edit/vue3-wangeditor-demo-1jwjzc?file=src%2Fcomponents%2FBasicEditor.vue,src%2FApp.vue
https://codesandbox.io/p/devbox/goofy-cohen-dx2gjt?workspaceId=f1f473a2-8900-4d7f-aad9-f88f1fcf65f4
### 复现文本
1+1=2
x = {-b \pm \sqrt{b^2-4ac} \over 2a}
### 问题图片
<img width="421" alt="image" src="https://github.com/user-attachments/assets/12f602fb-7239-42d3-b8b3-b89b0b81ddd5">

**Comment by cycleccc** [comment]
https://stackblitz.com/edit/vue3-wangeditor-demo-1jwjzc?file=src%2Fcomponents%2FBasicEditor.vue,src%2FApp.vue
https://codesandbox.io/p/devbox/goofy-cohen-dx2gjt?workspaceId=f1f473a2-8900-4d7f-aad9-f88f1fcf65f4
提供的 demo 里似乎没有对应的复现，方便把对应的复现补全吗

**Comment by LeonsCd** [comment]
感谢回复，
已补全如下
https://codesandbox.io/p/devbox/goofy-cohen-dx2gjt?workspaceId=f1f473a2-8900-4d7f-aad9-f88f1fcf65f4
我们看到的结果应该是一致的吧,如果不一致的话，那可能是我这边有点问题
<img width="1025" alt="image" src="https://github.com/user-attachments/assets/f6996e2d-63a4-46b3-ad56-0b5d04500112">

**Comment by cycleccc** [comment]
提供的沙盒似乎无法访问😂
![image](https://github.com/user-attachments/assets/431c4d23-8df7-4320-9be4-514475c233d6)

**Comment by LeonsCd** [comment]
> 提供的沙盒似乎无法访问😂 ![image](https://private-user-images.githubusercontent.com/62703840/389762445-431c4d23-8df7-4320-9be4-514475c233d6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI1ODcxNDgsIm5iZiI6MTczMjU4Njg0OCwicGF0aCI6Ii82MjcwMzg0MC8zODk3NjI0NDUtNDMxYzRkMjMtOGRmNy00MzIwLTliZTQtNTE0NDc1YzIzM2Q2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTI2VDAyMDcyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIzMDc5YzRkMGQxZmUzYjBjYzFkODRiM2ViNDE2YzQ0YjExNDBlMDY3NWViNGYzOTAyMTk5ZDg3MzRhMDk3MGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.kq-iKimhq97fMjDxlGG6hUUU3am8PhMjHyaAS6D2dEs)

不好意思，这下应该能看了，没注意

https://codesandbox.io/p/devbox/goofy-cohen-dx2gjt?workspaceId=f1f473a2-8900-4d7f-aad9-f88f1fcf65f4
