### ISSUE TITLE
在uniapp内安装使用wangEditor-next会出现button默认样式被覆盖导致样式错乱

### ISSUE THREAD

**Issue by beforeRun** [wangeditor-next/wangEditor-next#392]
## bug 描述

在uniapp项目中安装wangEditor-next，因为插件图标都是用的button按钮，导致样式错乱，而且使用:deep也无法穿透覆盖，请大佬看一下uniapp中使用wangEditor-next的问题。
![ff6cbce0975b64480ac4b78078207371](https://github.com/user-attachments/assets/092ec4a7-4514-4854-875e-3a69efb3a3a4)

## 你预期的样子是？

想到达，不要受到button默认按钮样式的控制。

## 系统和浏览器及版本号

uniapp，vue3版本

## wangEditor-next 版本

@wangeditor-next/editor": "^5.6.15,
@wangeditor-next/editor-for-vue": "^5.1.14,

## demo 能否复现该 bug ？

能/不能

- demo https://cycleccc.github.io/demo/

## 最小成本的复现步骤
1.创建uniapp项目
2.安装wangeditor-next
3.bug将会呈现

**Comment by beforeRun** [comment]
大佬，有时间给尽快看看在uniapp的这个问题吧，被困扰已久，其他富文本用起来不如wangEditor顺手，uniapp开发对富文本也是有需求的。

**Comment by cycleccc** [comment]
你方便看一下不，没怎么接触过 uniapp ，看下能不能出个最小复现沙盒 demo 我们一起看下。

**Comment by beforeRun** [comment]
经过uniapp插件作者帮忙解决了问题，需要将@wangeditor-next/editor/dist/css/style.css路径拷贝到template内，如<link href="static/editor/style.css" rel="stylesheet" />，这样的话，就不会被uniapp编译的时候覆盖掉了。

但是这样拷贝出来的话，就不能随着插件更新了，不知道大佬还有没有可优化方案。

**Comment by cycleccc** [comment]
![image](https://github.com/user-attachments/assets/8fe844a4-0521-4c33-a5f7-c8db1b29a20c)
在 uniapp 中这样导入不生效的吗

css 不更新也没关系，不会有大改动，自己维护一套反而更灵活。

**Comment by beforeRun** [comment]
是的，这样导入不生效，在组件内使用link导入static内的css后，将这个import给删除之后也不受影响了

**Comment by cycleccc** [comment]
项目内维护一套吧，也方便自定义样式。

**Comment by beforeRun** [comment]
好的，那就这样搞吧
