### ISSUE TITLE
请问Table标签有没有属性可以来作为标记位置

### ISSUE THREAD

**Issue by Sole-BadGuy** [wangeditor-next/wangEditor-next#396]
## 问题描述

请问Table标签有没有属性可以来作为标记位置 比如后端返回的html模板里包含3个table我需要通过标记位来判断哪个table被删除了 我使用id加到table上会被刷掉

## wangEditor 版本
最新

## 是否查阅了文档 ？
是

**Comment by cycleccc** [comment]
id 是 wangEditor 内部 vnode diff 更新用的。
自定义插件，在自定义插件的标签里定义一个自定义属性可以实现。
