### ISSUE TITLE
从别处拷贝文档到编辑器内。如果从钉钉文档拷贝一段文本，文本中包含超链接，那么后面的内容也都会加上超链接。并且获取出来的headers很多都是undefault

### ISSUE THREAD

**Issue by huangzhang-ops** [wangeditor-next/wangEditor-next#397]
## Bug Description

从别处拷贝文档到编辑器内。如果从钉钉文档拷贝一段文本，文本中包含文档超链接
如图
![image](https://github.com/user-attachments/assets/7451e35a-d8c8-461e-bbdd-196dc7fef30f)
拷贝过去就会出现异常
![image](https://github.com/user-attachments/assets/96d53dec-cc38-41bd-8dac-2a2d20bd57cf)
超链接后面的内容也都会加上超链接。
并且获取出来的headers很多都是undefined
![image](https://github.com/user-attachments/assets/2121be5d-b929-4952-a561-d1e20fd7ebac)

## What did you expect to happen?

*Please enter the details...*

## System, Browser, and Version

- Operating System
- Browser and Version

## wangEditor-next Version

*Please enter the details...*

## Can the demo reproduce the bug?

Yes/No

- Demo: https://cycleccc.github.io/demo/

## Online Demo

 - SandBox url: https://stackblitz.com/@cycleccc/collections/wangeditor

## Steps to Reproduce at Minimum Cost

- Step 1
- Step 2
- Step 3

**Comment by cycleccc** [comment]
可以附上对应的钉钉文档 url，方便复现

**Comment by huangzhang-ops** [comment]
查到了。因为从钉钉文档拷贝过来的html <a></a>不配对。获取出来的html中有个<a><a/>不配对导致的。已解决请忽略。
