### ISSUE TITLE
功能 : 视频添加居左居右居中位置控制（已在 wangeditor-next 实现）

### ISSUE THREAD

**Issue by cycleccc** [wangeditor-next/wangEditor-next#4]
相关 issue ：
https://github.com/wangeditor-team/wangEditor/issues/5259
https://github.com/wangeditor-team/wangEditor/issues/4456
https://github.com/wangeditor-team/wangEditor/issues/4058

**Comment by cycleccc** [comment]
原来的处理没有加入 text-align: center 属性的导出，现在在这里加了perf(issue 5259): video element default center，由于 elem type 的一些问题，后续还要继续处理。

**Comment by zpzyyzp** [comment]
非常期待这个功能！
不能调节视频的位置很不方便

**Comment by cycleccc** [comment]
@zpzyyzp 
我刚刚发布了新版本实现了视频位置调节，具体版本可以看  [wangeiditor-next](https://github.com/cycleccc/wangEditor-next) 沙盒示例，替换wangeditor及 vue/react

如果有帮助的话麻烦点个star，很需要这个😂

还有就是有兴趣的话可以一起来维护wangeditor，有完整的开发指南，有什么问题可以和我讨论或提issue。😬
