### ISSUE TITLE
插入自定义元素

### ISSUE THREAD

**Issue by yangzl96** [wangeditor-next/wangEditor-next#400]
## 问题描述

作者你好，请教一个问题，我使用wangeditor划了一段词例如:'abc'，弹出hover菜单，点击菜单的某一项后，使用自定义元素的方法 insetNode 插入了一个新的元素，元素的内容也是 'abc' ，自定义元素是显示了，但是，我再去划这个 'abc' ，就没有hover菜单了，这个能怎么处理呀 
## wangEditor 版本
wangeditor 5.1.23;
wangeditor/editor-for-vue: 5.1.12

## 是否查阅了文档 ？

（文档链接 [https://cycleccc.github.io/docs/](https://cycleccc.github.io/docs/) ）

是

## 最小成本的复现步骤

（请告诉我们，如何**最快的**复现该问题？）

- 步骤一
- 步骤二
- 步骤三

**Comment by Sole-BadGuy** [comment]
借楼  我自定义一个元素 用来包裹标记使用  比如 table外层包裹了一层这个自定义元素 在这个包裹的node后边回车输入值的时候 输入的值也会进入这个包裹元素里  期望的后边输入的值转换的元素应该是跟这个包裹元素同级

**Comment by Sole-BadGuy** [comment]
![1733103057352](https://github.com/user-attachments/assets/cb3c2cca-0cb0-4ed4-9f2f-67eb8fa30e81)

**Comment by cycleccc** [comment]
需要最小复现 demo ，看文字信息不够。
