### ISSUE TITLE
请问一下图片上传到文档中心后，通过img标签显示的，每次编辑器修改都会下载图片，这个有什么办法可以优化吗？

### ISSUE THREAD

**Issue by panxin226** [wangeditor-next/wangEditor-next#401]
## 问题描述
请问一下图片上传到文档中心后，通过img标签显示的，每次编辑器修改都会下载图片，这样应该会响应性能的吧？请问这个有什么办法可以优化吗？
*请输入遇到的问题...*

## wangEditor 版本

*请输入内容……*
最新
## 是否查阅了文档 ？

（文档链接 [https://cycleccc.github.io/docs/](https://cycleccc.github.io/docs/) ）

*是/否*
是
## 最小成本的复现步骤

（请告诉我们，如何**最快的**复现该问题？）
![image](https://github.com/user-attachments/assets/72b46e00-b53b-4940-9adc-3d8e969330fe)

https://github.com/user-attachments/assets/fe5019f8-2402-46e5-8c1a-a606ef783d68

- 步骤一
- 步骤二
- 步骤三

**Comment by cycleccc** [comment]
和 #309 相同，每次会全量更新，需要做 缓存 diff。在 #309 讨论吧
