### ISSUE TITLE
自定义一个元素 用来包裹标记使用 比如 table外层包裹了一层这个自定义元素 在这个包裹的node后边回车输入值的时候 输入的值也会进入这个包裹元素里 期望的后边输入的值转换的元素应该是跟这个包裹元素同级

### ISSUE THREAD

**Issue by Sole-BadGuy** [wangeditor-next/wangEditor-next#402]
## 问题描述
自定义一个元素 用来包裹标记使用 比如 table外层包裹了一层这个自定义元素 在这个包裹的node后边回车输入值的时候 输入的值也会进入这个包裹元素里 期望的后边输入的值转换的元素应该是跟这个包裹元素同级

## wangEditor 版本
最新

## 是否查阅了文档 ？
是
![Uploading 微信图片_20240318094656.jpg…]()
![Uploading 微信图片_20241114143342.jpg…]()

**Comment by Sole-BadGuy** [comment]
![微信图片_20240318094656](https://github.com/user-attachments/assets/df29c048-006c-4e88-bf8b-53d4f4b49c65)
![微信图片_20241114143342](https://github.com/user-attachments/assets/220c6151-5870-497c-b19a-52c2125dedb6)

**Comment by Sole-BadGuy** [comment]
![1733103057352](https://github.com/user-attachments/assets/91855c14-9ca0-4fad-a79f-57f0b20254f1)
![1733103159311](https://github.com/user-attachments/assets/1b249be0-e86d-4f5d-8906-b1c2e67d1566)

**Comment by Sole-BadGuy** [comment]
![1733107296410](https://github.com/user-attachments/assets/75030811-6437-42ed-82fb-023748834fe9)
![1733103159311](https://github.com/user-attachments/assets/de43be54-1b37-4d0e-98f7-1a7a5d6af55c)

**Comment by cycleccc** [comment]
意思是 789 这个 p 标签意外的包在了你的 自定义元素里吗。
可能需要最小复现 demo 才好定位。

**Comment by Sole-BadGuy** [comment]
找到问题了是table生成的时候多了个p标签 跟在后面导致 我包裹元素的时候去掉p标签就行了

**Comment by Sole-BadGuy** [comment]
> 意思是 789 这个 p 标签意外的包在了你的 自定义元素里吗。 可能需要最小复现 demo 才好定位。

找到问题了是table生成的时候多了个p标签 跟在后面导致 我包裹元素的时候去掉p标签就行了
