### ISSUE TITLE
请问这个plugin-link-card 插件没有做集成吗？

### ISSUE THREAD

**Issue by makefriend** [wangeditor-next/wangEditor-next#411]
## 问题描述
请问这个plugin-link-card 插件没有做集成吗？

*请输入遇到的问题...*

## wangEditor 版本

*[wangEditor-next](https://github.com/cycleccc/wangEditor-next)  5.6.12*

## 是否查阅了文档 ？

（文档链接 [https://cycleccc.github.io/docs/](https://cycleccc.github.io/docs/) ）

*是，根据 https://github.com/wangeditor-team/wangEditor-plugin-link-card 这个来操作的*

## 最小成本的复现步骤

（请告诉我们，如何**最快的**复现该问题？）

- 根据这个来集成 https://github.com/wangeditor-team/wangEditor-plugin-link-card

**Comment by cycleccc** [comment]
还没，我今天看下加到 packages 里吧

**Comment by makefriend** [comment]
好的，谢谢
