### ISSUE TITLE
可以添加个表格合并吗

### ISSUE THREAD

**Issue by superchenhongze** [wangeditor-next/wangEditor-next#43]
## 功能描述

现在的表格里面有增减行列，可以把表格的功能扩展个合并吗，可能合并需求不是很大，比较喜欢用这个富文本，但是比较菜，自己加的BUG太多，好几次都只能找个其它的编辑器

## 提炼几个功能点

- 表格合并单元格

## 原型图

*无*

## 可参考的案例

*无*

**Comment by cycleccc** [comment]
@jschyz https://github.com/cycleccc/wangEditor-next/issues/24
这个已经由 huihui 实现了

**Comment by cycleccc** [comment]
可以在 [demo](https://cycleccc.github.io/demo/) 或 readme 中的 对应框架沙盒 试用

**Comment by superchenhongze** [comment]
感谢
