### ISSUE TITLE
一个页面多个编辑器都进行初始化，并用v-show隐藏其中的编辑器，从1-5 5个编辑器如果第一个编辑器有表格则后面的编辑器中的表格无法拖动

### ISSUE THREAD

**Issue by DeveloperHu** [wangeditor-next/wangEditor-next#439]
## bug 描述

一个页面多个编辑器都进行初始化，并用v-show隐藏其中的编辑器，从1-5 5个编辑器如果第一个编辑器有表格则后面的编辑器中的表格无法拖动

## 你预期的样子是？

*每个编辑器中表格都能正常拖动*

## 系统和浏览器及版本号

- 操作系统
- 浏览器和版本

## wangEditor-next 版本

*5.6.17   *
editor for vue2  1.02
## demo 能否复现该 bug ？

能/不能

- demo https://cycleccc.github.io/demo/

## 在线 demo

- 沙盒链接: https://stackblitz.com/@cycleccc/collections/wangeditor

## 最小成本的复现步骤

- 步骤一
- 步骤二
- 步骤三

**Comment by cycleccc** [comment]
方便的话可以用沙盒环境出一个 demo
