### ISSUE TITLE
能否为 代码块 中所选中的代码，增加快捷键缩进的功能，包含增加和减少缩减，类似编辑器一样，Shift+Tab 就是减少缩进，Tab就是增加缩进

### ISSUE THREAD

**Issue by beilika** [wangeditor-next/wangEditor-next#454]
比如下面这种情况，就需要减少缩进，感觉这个需求还挺多的
![image](https://github.com/user-attachments/assets/922f78d2-a913-4be5-937f-35ccbdc62be2)

**Comment by cycleccc** [comment]
添加了基础的多选 tab 增加缩进功能，shift + tab 事件监听似乎有些问题，所以没加进去，这个还得再看看。
https://github.com/user-attachments/assets/5d9c97aa-b24c-48e0-a959-e1d4749062af
