### ISSUE TITLE
插件markdown使用类型问题

### ISSUE THREAD

**Issue by chenxq-297** [wangeditor-next/wangEditor-next#457]
vue3环境步骤：：
1.pnpm i @wangeditor/plugin-md 
2.
//导入包
import { Boot} from '@wangeditor-next/editor'
import markdownModule from '@wangeditor/plugin-md'
//创建时
const handleCreated = (editor: any) => {
  editorRef.value = editor; // 记录 editor 实例，重要！
 //注册插件
  Boot.registerModule(markdownModule);
  editor.insertKeys = ['markdown']
};

markdownModule注册不成功 且类型不匹配
![image](https://github.com/user-attachments/assets/ad342a0f-f58d-4367-9752-3cc48c87558a)

**Comment by cycleccc** [comment]
![image](https://github.com/user-attachments/assets/fb40af02-2773-4586-bbfc-c03b498ddfe2)
[wangeditor-next](https://github.com/cycleccc/wangEditor-next) 里用不了 wangeditor 的 相关插件哦，需要基于 [wangeditor-next](https://github.com/cycleccc/wangEditor-next) 的插件。
如 [@wangeditor-next/plugin-markdown](https://www.npmjs.com/package/@wangeditor-next/plugin-markdown)

**Comment by chenxq-297** [comment]
感谢更新文档

**Comment by chenxq-297** [comment]
![image](https://github.com/user-attachments/assets/5ca39ba6-754d-483d-b273-3551b41a3265)
大佬有时间更新一下文档

**Comment by cycleccc** [comment]
好的，readme 代码已更新，npm readme 会在下次版本发布时同步更新
