### ISSUE TITLE
無法引用IToolbarConfig

### ISSUE THREAD

**Issue by CCYO** [wangeditor-next/wangEditor-next#458]
## 问题描述

您好，在遵照「[工具攔配置](https://cycleccc.github.io/docs/guide/toolbar-config)」進行編寫時，根據範例
`import { IToolbarConfig } from '@wangeditor-next/editor'`

希望引用IToolbarConfig，卻顯示以下錯誤，無法正確引用。

export 'IToolbarConfig' (imported as 'IToolbarConfig') was not found in '@wangeditor-next/editor' (possible exports: Boot, DomEditor, SlateEditor, SlateElement, SlateLocation, SlateNode, SlatePath, SlatePoint, SlateRange, SlateText, SlateTransforms, Toolbar, createEditor, createToolbar, createUploader, default, genModalButtonElems, genModalInputElems, genModalTextareaElems, i18nAddResources, i18nChangeLanguage, i18nGetResources, t)

## wangEditor 版本

v5.6.19

## 是否查阅了文档 ？

（文档链接 [https://cycleccc.github.io/docs/guide/toolbar-config](https://cycleccc.github.io/docs/guide/toolbar-config) ）

是

## 最小成本的复现步骤

- 步骤一
`import { IToolbarConfig } from '@wangeditor-next/editor'`
![q](https://github.com/user-attachments/assets/5853550c-564c-4792-8b3b-7931bcd60081)

**Comment by cycleccc** [comment]
IToolbarConfig 是个 d.ts 中的类型定义，在 js 中引入应该没有效果，如果不实用 TS 的话不需要引入相关的类型定义
