### ISSUE TITLE
如何定义一个块输入 然后块里面可以逐字输入 删除时整个块删除 不能逐字删除，请问有什么思路呢

### ISSUE THREAD

**Issue by DeveloperHu** [wangeditor-next/wangEditor-next#461]
## 问题描述

如何自定义块实现整个块输入删除

## wangEditor 版本

Last

## 是否查阅了文档 ？

（文档链接 [https://cycleccc.github.io/docs/](https://cycleccc.github.io/docs/) ）

*是/否*

## 最小成本的复现步骤

（请告诉我们，如何**最快的**复现该问题？）

- 步骤一
- 步骤二
- 步骤三

**Comment by cycleccc** [comment]
实现一个类似代码块的自定义元素 写一个 plugin 监听 delete 事件，删除自定义元素中的文字，具体看以下代码
https://github.com/cycleccc/wangEditor-next/blob/3b4b06f82d7ec29335b305a63bce307b8970f26b/packages/basic-modules/src/modules/code-block/plugin.ts#L27
