### ISSUE TITLE
外部复制到编辑器的表格无法合并、删除行列等操作

### ISSUE THREAD

**Issue by 1295385531** [wangeditor-next/wangEditor-next#471]
【腾讯文档】餐饮茶饮烘焙
https://docs.qq.com/sheet/DWFhXQW5IWGVrREFk
表格链接

![image](https://github.com/user-attachments/assets/fc754b6f-d6bf-46ce-bec6-074a10bbb539)

**Comment by cycleccc** [comment]
和 https://github.com/cycleccc/wangEditor-next/issues/375 相同，我最近会处理这个问题。
