### ISSUE TITLE
上传多张图片或多个视频时的bug

### ISSUE THREAD

**Issue by anai1943** [wangeditor-next/wangEditor-next#472]
之前提交的issue：https://github.com/cycleccc/wangEditor-next/issues/444

更新到"@wangeditor-next/editor": "^5.6.21"后，上传2张图片，前端只请求了一次，发送了2个file字段，后端我暂时没有处理多个file，只响应了一个地址，前端图片也只显示一张，没有报错信息。

能否和 https://github.com/cycleccc/server 一样，每次上传一个file，响应一个地址。如果是一次发送多个file，上传多个视频时，请求时间会比较长。

还有，按目前的清空，后端要响应什么样的数据格式给前端才能多个图片或视频都能正常显示？

https://github.com/user-attachments/assets/3dc1cd2e-0507-42e5-86b6-a5ec76c02e5c

https://github.com/user-attachments/assets/3fff6e46-9e75-4e51-b5a1-2709c0427d1e

**Comment by cycleccc** [comment]
https://github.com/cycleccc/server 更新了吗，用最新的 server 试试

**Comment by anai1943** [comment]
> https://github.com/cycleccc/server 更新了吗，用最新的 server 试试

试了下，最新的server也是多个文件发送一次请求，我再看看后端怎么写的。

**Comment by cycleccc** [comment]
以前的逻辑是分次上传的，分次上传不方便使用 Uppy 的部分功能，如 最大文件上传数量这个配置以前就是失效的，现在改成了多个文件发送一次请求，如果时间长的话 Uppy 也支持断点续传，这个详细的得看看 Uppy 的使用文档

**Comment by myh110** [comment]
: Cannot add the duplicate file '16431953210816.jpg', it already exists

不能重复上传图片？

**Comment by kooriookami** [comment]
> 以前的逻辑是分次上传的，分次上传不方便使用 Uppy 的部分功能，如 最大文件上传数量这个配置以前就是失效的，现在改成了多个文件发送一次请求，如果时间长的话 Uppy 也支持断点续传，这个详细的得看看 Uppy 的使用文档

现在是不能配置多个接口上传了吗
