### ISSUE TITLE
bug:合并后，使用getHTML获取html字符，再用setHTML回填，td中style="display:none"会被编辑器丢掉，导致合并掉的格子又会显示

### ISSUE THREAD

**Issue by cycleccc** [wangeditor-next/wangEditor-next#48]
合并后，使用getHTML获取html字符，再用setHTML回填，td中style="display:none"会被编辑器丢掉，导致合并掉的格子又会显示
![image](https://github.com/user-attachments/assets/7f6750ea-087d-4f69-bfc4-c96dca7c1f08)

_Originally posted by @whsqjss in https://github.com/cycleccc/wangEditor-next/issues/24#issuecomment-2240933589_

**Comment by cycleccc** [comment]
@whsqjss 我刚在 [set-html-demo](https://cycleccc.github.io/demo/set-html.html) 里试了一下在编辑器中表现是正常的
能再试一下 demo网页 里的 [set-html-demo](https://cycleccc.github.io/demo/set-html.html) 和 [get-html-demo](https://cycleccc.github.io/demo/get-html.html) 尝试复现吗
我试了一下刚开始好像复现了,后面又怎么都复现不出来了

**Comment by cycleccc** [comment]
可以明确的是,如果把现有的合并单元格后的 html 扔到旧版的 wangEditor 里肯定没处理溢出的 td.

**Comment by topzhanghj** [comment]
好奇怪呀，为什么在[demo](https://cycleccc.github.io/demo/index.html)中没有合并单元格的功能呢
<img width="761" alt="image" src="https://github.com/user-attachments/assets/13e86e1a-009d-47bb-9283-3e43c05cb5c0">

不过通过在 [react-demo](https://stackblitz.com/edit/react-4osjqn?file=README.md)中生成一个html，然后set到demo中，就可以复现出来
<img width="1587" alt="image" src="https://github.com/user-attachments/assets/a4fa92ea-0d58-4b78-8686-9b5e97d857b9">

**Comment by cycleccc** [comment]
@topzhanghj  我发布了 5.3.12 alpha ，暂时revert了 表格合并功能
有多编辑器和框架使用的 bug ，得先解决一下。
这个 溢出的 bug 好解决，大概率是判断条件漏了。
得先解决上面两个问题。

**Comment by cycleccc** [comment]
> 好奇怪呀，为什么在[demo](https://cycleccc.github.io/demo/index.html)中没有合并单元格的功能呢 <img alt="image" width="761" src="https://private-user-images.githubusercontent.com/55379862/352142007-13e86e1a-009d-47bb-9283-3e43c05cb5c0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIzOTE0MzUsIm5iZiI6MTcyMjM5MTEzNSwicGF0aCI6Ii81NTM3OTg2Mi8zNTIxNDIwMDctMTNlODZlMWEtMDA5ZC00N2JiLTkyODMtM2U0M2MwNWNiNWMwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzMxVDAxNTg1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY0MjcwMjI4YzMwN2JiMjk2YTE5MzU4NTA2ZWRlYmYzNjRhNmQwNjA2NjM4YmI3NzBhZThjZTJhMWY1NzQ0MjEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.yZP13KVmFB1BCv4eUhHrD46sPl77zKRaAwQSpIbaegc">
> 
> 不过通过在 [react-demo](https://stackblitz.com/edit/react-4osjqn?file=README.md)中生成一个html，然后set到demo中，就可以复现出来 <img alt="image" width="1587" src="https://private-user-images.githubusercontent.com/55379862/352143519-a4fa92ea-0d58-4b78-8686-9b5e97d857b9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIzOTE0MzUsIm5iZiI6MTcyMjM5MTEzNSwicGF0aCI6Ii81NTM3OTg2Mi8zNTIxNDM1MTktYTRmYTkyZWEtMGQ1OC00Yjc4LTg2ODYtOWI1ZTk3ZDg1N2I5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzMxVDAxNTg1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRmYzY2MmE5Mzk0MmJmZmNkMjE4MTY3M2VlM2VmODllMzY3MDIzOTRmOGYyNDY0MjNhYjRlNDU5ZDIxNGFlMjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.-1_-Tf7iBIPRloTlRIxQcC74ndvu38iB03b2xZJiTqg">

这里会出现这个现象是因为我在 5.3.12 alpha 时回滚了合并单元格相关的逻辑，复制进来的表格自然是溢出的（因为没有被处理）有需要的话可以在 5.1.13 试试。😀

**Comment by cycleccc** [comment]
@lijiangpeng7

**Comment by ljp-777** [comment]
![WechatIMG5](https://github.com/user-attachments/assets/be35cb07-2074-431e-adc8-5a097e5eb7d8)
我在本地这样修复了一下，经测试可以解决问题
