### ISSUE TITLE
bug: 当编辑器设置为 scroll: false 时，悬浮框 hoverbar 位置出现错位。（已在 wangEditor-next 实现）

### ISSUE THREAD

**Issue by cycleccc** [wangeditor-next/wangEditor-next#53]
相关 issue:
https://github.com/wangeditor-team/wangEditor/issues/5072
相关 pr:
https://github.com/wangeditor-team/wangEditor/pull/5098

**Comment by cycleccc** [comment]
已实现，看到这个 issue 的小伙伴记得设置 scroll:false 时别定死宽度，不然内容会溢出。

**Comment by cycleccc** [comment]
https://github.com/cycleccc/wangEditor-next/issues/55#issuecomment-2254190838
@hanpandeng 可能问题是因为这个 fix 导致的，小问题，我看看，后续版本补上，你可以先用 wangeditor 的样式，那套样式文件复制下来保存在自己项目里也是一样的。

> [自定义样式](https://cycleccc.github.io/docs/guide/content#%E8%87%AA%E5%AE%9A%E4%B9%89%E6%A0%B7%E5%BC%8F)

**Comment by cycleccc** [comment]
![image](https://github.com/user-attachments/assets/5fb8a7fa-b593-43b2-88f8-eade4cf24835)
这一行的问题，我改掉，这次不会这么快发版了，打算先升级一下node 版本、nanoid版本还有完善单测再发版。
可以先用样式覆盖或是 [自定义样式](https://cycleccc.github.io/docs/guide/content#%E8%87%AA%E5%AE%9A%E4%B9%89%E6%A0%B7%E5%BC%8F) 处理一下。

**Comment by hanpandeng** [comment]
> [#55 (comment)](https://github.com/cycleccc/wangEditor-next/issues/55#issuecomment-2254190838) @hanpandeng 可能问题是因为这个 fix 导致的，小问题，我看看，后续版本补上，你可以先用 wangeditor 的样式，那套样式文件复制下来保存在自己项目里也是一样的。
> 
> > [自定义样式](https://cycleccc.github.io/docs/guide/content#%E8%87%AA%E5%AE%9A%E4%B9%89%E6%A0%B7%E5%BC%8F)

那我先引用 wangEditor 的样式，等你把这个问题更新后我再引用你的
