### ISSUE TITLE
视频设置宽度后，再次进入编辑，会丢失样式，比如我设置30%，重新进入后style直接置空了

### ISSUE THREAD

**Issue by gonglb** [wangeditor-next/wangEditor-next#57]
## bug 描述

视频设置宽度后,提取的HTML中，是有style="width:100%"，重新进入编辑，并设置提取的HTML，进入后style直接置空了
还有个问题，提交的html中  video标签上的width和height还是auto ,是否不应该把100%放在style上，应该直接放在width="100%",height应该也有同样的问题，大佬啥时候帮忙辛苦看一下

## 你预期的样子是？

保留该有的style

## 系统和浏览器及版本号

- 操作系统
- 浏览器和版本

## wangEditor-next 版本

5.3.11

## demo 能否复现该 bug ？

能

- 步骤一
- 步骤二
- 步骤三

**Comment by cycleccc** [comment]
已复现，疏忽了，单测没覆盖到。

**Comment by gonglb** [comment]
哈哈哈，修水管，还有就是width默认能不能直接搞成100%，不然我的编辑器窄了，直接超出编辑器了，有点丑

**Comment by cycleccc** [comment]
这个修复在5.3.13 上线了，方便的话可以测一下，对应的单测还没上，有很多单侧要补

**Comment by cycleccc** [comment]
> 哈哈哈，修水管，还有就是width默认能不能直接搞成100%，不然我的编辑器窄了，直接超出编辑器了，有点丑

width:auto 不能满足需求吗，能截个图看一下不，我设置浏览器尺寸也不好复现。

**Comment by cycleccc** [comment]
> 哈哈哈，修水管，还有就是width默认能不能直接搞成100%，不然我的编辑器窄了，直接超出编辑器了，有点丑

没办法，时间有限，所以现在就想等稳定下来，先不加新功能，专心补单测了。🤯

**Comment by cycleccc** [comment]
再次验证了一遍，应该没问题了，后续 默认值的问题，可以另提一个 issue，这个issue 我先关了哈 😀

**Comment by yuanprogrammer** [comment]
> > 哈哈哈，修水管，还有就是width默认能不能直接搞成100%，不然我的编辑器窄了，直接超出编辑器了，有点丑
> 
> width:auto 不能满足需求吗，能截个图看一下不，我设置浏览器尺寸也不好复现。

大部分场景都是100%吧，自适应编辑器宽度，不然每次都会超出编辑器宽度
