### ISSUE TITLE
TODO：nanoid 版本太低，升级 nanoid版本（已在 wangeditor-next 实现）

### ISSUE THREAD

**Issue by cycleccc** [wangeditor-next/wangEditor-next#59]
相关 issue：
https://github.com/wangeditor-team/wangEditor/issues/5787

**Comment by cycleccc** [comment]
nanoid 已升级最新版

**Comment by gonglb** [comment]
无语，升级这个，我项目报错了，本地node我的版本是16，不兼容，其他兄弟如果也遇到了，可以在package.json 增加 "resolutions": {
    "nanoid": "3.0.0"
  }
  来锁定nodeid版本

**Comment by cycleccc** [comment]
node16 确实需要锁版本
