### ISSUE TITLE
请教一下，如何实现图片(尺寸20px的小图)和文字垂直居中对齐，目前只有文字的对齐方式，没有flex布局相关功能

### ISSUE THREAD

**Issue by zhengnan0627** [wangeditor-next/wangEditor-next#62]
## 功能描述
实现图片和单行文字垂直居中对齐
*请输入内容……*
通过添加样式 display: flex;align-items: center;实现垂直居中，但是这些样式如何设置到富文本内容内，通过新增菜单的方式能实现吗？
## 提炼几个功能点

- 功能1
- 功能2
- 功能3

## 原型图

*涉及到 UI 改动的功能，请一定提供原型图。原型图能表明功能即可，不要求规范和美观*

## 可参考的案例

*是否已有可参考的案例（如其他编辑器），有的话请给出链接*

**Comment by cycleccc** [comment]
![image](https://github.com/user-attachments/assets/85c99a32-f281-4435-a631-935966d3f97f)
这样不行吗

**Comment by zhengnan0627** [comment]
> ![image](https://private-user-images.githubusercontent.com/62703840/353321448-85c99a32-f281-4435-a631-935966d3f97f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIzMTk0MzQsIm5iZiI6MTcyMjMxOTEzNCwicGF0aCI6Ii82MjcwMzg0MC8zNTMzMjE0NDgtODVjOTlhMzItZjI4MS00NDM1LWE2MzEtOTM1OTY2ZDNmOTdmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzMwVDA1NTg1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJmYjQ4NDI1NmU4OTVjMTU1N2VjNmZlMDllZDdhZDVmZDFiMWE2N2MyN2M2MjFkMDhmM2FlMTVlZmZhZWE0N2UmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.HZ_f2ZiquTpq3CkPnZt9KLlD4--3UZyc4gBDfHLUyJs) 这样不行吗



> ![image](https://private-user-images.githubusercontent.com/62703840/353321448-85c99a32-f281-4435-a631-935966d3f97f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIzMTk0MzQsIm5iZiI6MTcyMjMxOTEzNCwicGF0aCI6Ii82MjcwMzg0MC8zNTMzMjE0NDgtODVjOTlhMzItZjI4MS00NDM1LWE2MzEtOTM1OTY2ZDNmOTdmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzMwVDA1NTg1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJmYjQ4NDI1NmU4OTVjMTU1N2VjNmZlMDllZDdhZDVmZDFiMWE2N2MyN2M2MjFkMDhmM2FlMTVlZmZhZWE0N2UmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.HZ_f2ZiquTpq3CkPnZt9KLlD4--3UZyc4gBDfHLUyJs) 这样不行吗

这种不是在同一行内，我是想把30px的小图当做标题前面的icon使用
![image](https://github.com/user-attachments/assets/7f905518-ebd5-4d2b-9021-68924afa1e2d)
zh实现这种展示形式

**Comment by zhengnan0627** [comment]
顺便提一下，自定义修改图片尺寸的feat目前有个bug，第二次修改时输入框默认值为30(第一次输入的数值)+'px'，导致直接点击确认按钮赋值错误，变回了auto，我目前使用replace替换px为空解决了这个问题

**Comment by cycleccc** [comment]
> 顺便提一下，自定义修改图片尺寸的feat目前有个bug，第二次修改时输入框默认值为30(第一次输入的数值)+'px'，导致直接点击确认按钮赋值错误，变回了auto，我目前使用replace替换px为空解决了这个问题

嗯，复现了，这个我记录一下，这两天改掉。字符串处理逻辑多了就乱了，这块还没补上测试，再补其它地方的。

**Comment by zhengnan0627** [comment]
> > 顺便提一下，自定义修改图片尺寸的feat目前有个bug，第二次修改时输入框默认值为30(第一次输入的数值)+'px'，导致直接点击确认按钮赋值错误，变回了auto，我目前使用replace替换px为空解决了这个问题
> 
> 嗯，复现了，这个我记录一下，这两天改掉。字符串处理逻辑多了就乱了，这块还没补上测试，再补其它地方的。

辛苦ღ( ´･ᴗ･` )，  我上面那种同一行内align-items: center可以通过哪种方式实现呢，目前我再看自定义表情，把表情当成行前面的icon使用，这个思路可行吗

**Comment by cycleccc** [comment]
可以单独造一个标题数据结构，就模仿着 wangeditor 里 独占一行的元素写就行了 具体看 [自定义数据结构](https://cycleccc.github.io/docs/guide/node-define)
在 wangeditor 里做内置的话应该暂时不考虑，我看其它富文本编辑器也没内置这个的。

**Comment by cycleccc** [comment]
> > > 顺便提一下，自定义修改图片尺寸的feat目前有个bug，第二次修改时输入框默认值为30(第一次输入的数值)+'px'，导致直接点击确认按钮赋值错误，变回了auto，我目前使用replace替换px为空解决了这个问题
> > 
> > 
> > 嗯，复现了，这个我记录一下，这两天改掉。字符串处理逻辑多了就乱了，这块还没补上测试，再补其它地方的。
> 
> 辛苦ღ( ´･ᴗ･` )， 我上面那种同一行内align-items: center可以通过哪种方式实现呢，目前我再看自定义表情，把表情当成行前面的icon使用，这个思路可行吗

我都忘了有这个功能，维护了几个月没碰过这个东西🤣，很好的思路，比自定义数据结构方便的多

**Comment by zhengnan0627** [comment]
> > > > 顺便提一下，自定义修改图片尺寸的feat目前有个bug，第二次修改时输入框默认值为30(第一次输入的数值)+'px'，导致直接点击确认按钮赋值错误，变回了auto，我目前使用replace替换px为空解决了这个问题
> > > 
> > > 
> > > 嗯，复现了，这个我记录一下，这两天改掉。字符串处理逻辑多了就乱了，这块还没补上测试，再补其它地方的。
> > 
> > 
> > 辛苦ღ( ´･ᴗ･` )， 我上面那种同一行内align-items: center可以通过哪种方式实现呢，目前我再看自定义表情，把表情当成行前面的icon使用，这个思路可行吗
> 
> 我都忘了有这个功能，维护了几个月没碰过这个东西🤣，很好的思路，比自定义数据结构方便的多

好的感谢，我再去研究研究
