### ISSUE TITLE
bug：换行或者插入表格之类，控制台报错 Cannot find a descendant at path [1] in node

### ISSUE THREAD

**Issue by sunflybird** [wangeditor-next/wangEditor-next#64]
## bug 描述

*换行或者插入表格之类，控制台报错 Cannot find a descendant at path [1] in node*

## 你预期的样子是？

*不在报错*

## 系统和浏览器及版本号

- 操作系统：win10
- 浏览器和版本：chrome最新

## wangEditor-next 版本

*5.3.13*
"@wangeditor-next/editor": "^5.3.13",
"@wangeditor-next/editor-for-vue2": "^1.0.2",
"@wangeditor-next/plugin-upload-attachment": "^1.1.0",

## demo 能否复现该 bug ？

不能

## 最小成本的复现步骤

- 步骤一  回车或者插入，只要是不在第一行输入，就会出现报错
- 
<img width="1262" alt="a95737b025d60702aafbf5fce037cbc" src="https://github.com/user-attachments/assets/35e28b38-068b-4d31-abcd-6e6c9aa61e3c">

https://github.com/user-attachments/assets/5d96f172-c9ef-43ad-a0f0-e1d50b75be68

**Comment by cycleccc** [comment]
你好，能尝试用这个 [demo](https://stackblitz.com/edit/vue2-vite-starter-5zsve3?file=package.json) 复现一下吗，我在里面安装了你描述里的对应版本。

**Comment by cycleccc** [comment]
可能是有依赖缓存，建议查看 node_module 删除旧版本更新新版本试试
