### ISSUE TITLE
bug：多编辑器场景下分别插入表格，在表格中输入会立马失去焦点

### ISSUE THREAD

**Issue by flydeemon** [wangeditor-next/wangEditor-next#65]
## bug 描述

多编辑器场景下分别插入表格，在表格中输入会立马失去焦点

## 你预期的样子是？

多个编辑器不会被相互影响，在编辑器中正常交互

## 系统和浏览器及版本号

- 操作系统
- 浏览器和版本

## wangEditor-next 版本

 "@wangeditor-next/editor": "^5.3.13",
 "@wangeditor-next/editor-for-react": "^1.0.6",

## demo 能否复现该 bug ？

能

- demo https://cycleccc.github.io/demo/multi-editor.html

## 最小成本的复现步骤

<img width="1099" alt="image" src="https://github.com/user-attachments/assets/44fb782f-a03a-43a6-b152-8a71ac4ff3e8">

**Comment by cycleccc** [comment]
以复现，上周处理了[多编辑器文字相关](https://github.com/cycleccc/wangEditor-next/issues/60)的  bug，多编辑器表格问题需要更深层的处理，将多编辑器监听事件隔离开,最近会安排时间处理。

**Comment by cycleccc** [comment]
更新了 5.3.14 可以试试，现在table 切换不会有失焦问题了
