### ISSUE TITLE
Bug: vue3 包缺失 d.ts 声明文件（已在 wangEditor-next 实现）

### ISSUE THREAD

**Issue by cycleccc** [wangeditor-next/wangEditor-next#7]
状态
wangeditor/editor-for-vue 待合并pr
wangeditor-next/editor-for-vue 已合并pr
描述
相关 issue https://github.com/wangeditor-team/wangEditor/issues/5673

**Comment by cycleccc** [comment]
已发布新版本

**Comment by anyluckwell** [comment]
![Uploading 1725422395895.jpg…]()
wangeditor-next 样式全乱的

**Comment by cycleccc** [comment]
@anyluckwell 图片格式乱了
![image](https://github.com/user-attachments/assets/a1931c99-d3e6-411d-8179-dfe6ccccae17)

1. 重新贴一下图片
2. 使用 [在线 demo](https://stackblitz.com/edit/vue3-wangeditor-demo-8emmc7)  尝试复现
3. 可以再开一个 issue 详细说一下
