### ISSUE TITLE
Bug：mac safari 微信截图粘贴后 base 64 转为了 blob:http://XXXX 

### ISSUE THREAD

**Issue by cycleccc** [wangeditor-next/wangEditor-next#70]
相关 issue：
https://github.com/wangeditor-team/wangEditor/issues/4474

难点：
没有 mac 设备 。。。

**Comment by wjw020206** [comment]
我尝试解决一下

**Comment by wjw020206** [comment]
这个问题的原因：
Safari 浏览器的 beforeinput 事件的 DataTransfer 与 Chrome、Firefox 实现存在差异导致了这个问题，以下是问题具体描述
https://github.com/w3c/input-events/issues/120
