### ISSUE TITLE
Bug：特殊格式内容 setHtml 报错

### ISSUE THREAD

**Issue by cycleccc** [wangeditor-next/wangEditor-next#72]
相关 issue：
https://github.com/wangeditor-team/wangEditor/issues/5922#issuecomment-2266345537

描述：
原 issue 是 setHtml 渲染错位，在 [wangeditor-next](https://github.com/cycleccc/wangEditor-next) 试验后发现 setHtml 报错，可能涉及过往某个标签的改动所影响。

**Comment by shangcj1992** [comment]
感谢给出建议。
