### ISSUE TITLE
图片修改尺寸使用功能问题 

### ISSUE THREAD

**Issue by wenqiang233** [wangeditor-next/wangEditor-next#73]
## 问题描述
图片修改尺寸功能，填写数字默认px控制图片大小，但是再次点击修改尺寸功能，弹窗展示宽度“数字+px“。当再次修改数值不删除px或者不修改数值直接确认，修改无效并图片大小变成auto。猜想应该是无法识别px，当再次查看或者修改尺寸时必须删除px。影响用户体验。

## wangEditor 版本
wangEditor-next最新版

## 是否查阅了文档 ？

是

## 最小成本的复现步骤

- 步骤一：点击图片修改尺寸
- 步骤二：填写数字，确认提交 
- 步骤三：再次点开这个图片修改尺寸
- 步骤四：不删除px修改数字或直接点击确认，图片大小变成auto。

**Comment by cycleccc** [comment]
周中修了，还没发版，周末发版

**Comment by cycleccc** [comment]
发布了5.3.14 修复了图片尺寸判定问题，你可以更新版本试试，没问题后可以关闭这个 issue，或几天后我会关闭这个 issue

**Comment by wenqiang233** [comment]
> 发布了5.3.14修复了图片尺寸判定问题，你可以更新版本试试，没问题后可以关闭这个问题，或者过几天我会关闭这个问题

只有宽度可以设置，高度设置无效。
