### ISSUE TITLE
图片修改尺寸功能，高度修改无效

### ISSUE THREAD

**Issue by wenqiang233** [wangeditor-next/wangEditor-next#74]
## bug 描述

图片编辑，修改尺寸功能高度设置无效，设置高度后不会改变图片尺寸

## 你预期的样子是？

图片编辑，修改尺寸功能填写宽度高度可以 自由设置尺寸

## 系统和浏览器及版本号

谷歌浏览器等。。。

## wangEditor-next 版本

wangEditor-next最新版

## demo 能否复现该 bug ？

能

## 最小成本的复现步骤

- 步骤一 ：点击图片修改尺寸功能
- 步骤二：高度填写数字
- 步骤三：点击确定后图片尺寸未发生变化，未添加相应css

**Comment by cycleccc** [comment]
这个涉及到了 table 嵌套的兼容，确实还是应该以 image 自身为主，具体该怎么做还得再看看，有兴趣修复一下这个问题吗😀

**Comment by wenqiang233** [comment]
> 这个涉及到了 table 嵌套的兼容，确实还是应该以 image 自身为主，具体该怎么做还得再看看，有兴趣修复一下这个问题吗😀

如果高度无效可以先禁止填写或去除。主要精通后端开发，前端知识只是了解基础。如有开发文档可以尝试改一下。如果影响其他功能不想改内部，可以提供监听API。由开发者自己根据项目补充功能

**Comment by cycleccc** [comment]
下周处理

**Comment by cycleccc** [comment]
更新了 5.4.2 处理了这个问题，table 嵌套 图片 还有更多的问题要处理，先放开图片高度设置了。
