### ISSUE TITLE
希望增加表格边框

### ISSUE THREAD

**Issue by shitiandmw** [wangeditor-next/wangEditor-next#75]
## 功能描述

在表格的属性设置条上，增加一个边框的属性，选中后，表格有明显的边框

## 原型图

![image](https://github.com/user-attachments/assets/3b093d94-1966-4fb3-845c-1d9ae2e5841d)

**Comment by cycleccc** [comment]
有相关的 pr  ，还有点小问题需要处理，这周会看下，解决。
https://github.com/cycleccc/wangEditor-next/pull/71

**Comment by shitiandmw** [comment]
静候佳音

**Comment by cycleccc** [comment]
已在 [5.4.1](https://www.npmjs.com/package/@wangeditor-next/editor/v/5.4.1) 实现

**Comment by cycleccc** [comment]
这个 issue 先关了，对于表格边框功能 ui 和 功能 有什么新的 bug 或提升可以再提 issue
