### ISSUE TITLE
从WangEditor@5.1.23 迁移过来报错 Error: Cannot resolve a DOM node from Slate node: {"text":"","fontSize":"11px"}

### ISSUE THREAD

**Issue by wjw020206** [wangeditor-next/wangEditor-next#80]
## 问题描述

浏览器控制台错误信息
```
index.esm.js:50 Uncaught (in promise) Error: Cannot resolve a DOM node from Slate node: {"text":"","fontSize":"11px"}
    at Object.toDOMNode (index.esm.js:50:34600)
    at Object.toDOMPoint (index.esm.js:50:35548)
    at Object.toDOMRange (index.esm.js:50:35141)
    at rI (index.esm.js:50:67871)
    at eval (index.esm.js:50:83228)
```

报错有两处，目前已在代码中找到这两处报错，如果把这两处注释掉则正常
第一处
```js
/** 初始化编辑器
   * @param {Object} editor 编辑器实例对象
   */
  const initEditor = (editor) => {
    editorRef.value = Object.seal(editor);
    getToolBarConfig(editorRef.value);

   // 此处 editorRef.value.setHtm() 导致报错
    editorRef.value.setHtml(
      `<p style='line-height: 1.5;'><span style="font-size: 11px;"></span></p>`,
    );
    editorRef.value.focus();
  };
```

第二处
```js
/** 初始化数据
   * @param {Object} data
   */
  const initData = (data) => {
    updateDate.value = data.modifyTime;
    title.value = data.name === '无标题' ? '' : data.name;
   // 此处报错，content 是 Editor 标签 v-model的属性
    content.value = data.content;
    creatorId.value = data.creatorId;
    fileId.value = data.id;
  };
```

## wangEditor 版本

"@wangeditor-next/editor": "^5.3.14",
"@wangeditor-next/editor-for-vue2": "^1.0.2",

## 是否查阅了文档 ？

（文档链接 [www.wangeditor.com](https://cycleccc.github.io/docs/) ）

*是*

**Comment by wjw020206** [comment]
我尝试降级 @wangeditor-next/editor 版本到 5.3.13，这个问题就没有了，应该是 BUG

**Comment by cycleccc** [comment]
是的，这个是以前的一个 bug，我这两天看一下，会修复。

**Comment by wjw020206** [comment]
> 是的，这个是以前的一个 bug，我这两天看一下，会修复。

感谢作者大大的付出，如果可以的话请尽快修复，因为我目前降级到 5.3.13 版本中存在合并单元格保存到后台，再从后台返回的数据渲染后因为合并单元格导致删除单元格又回来了，5.3.14 中没有这个问题

**Comment by cycleccc** [comment]
https://www.npmjs.com/package/@wangeditor-next/editor/v/5.3.15-experimental.15 发布了个实验版，在 沙盒里试了没有这个问题，你可以先切换这个试试。

**Comment by wjw020206** [comment]
> https://www.npmjs.com/package/@wangeditor-next/editor/v/5.3.15-experimental.15 发布了个实验版，在 沙盒里试了没有这个问题，你可以先切换这个试试。

好的，感谢感谢

**Comment by cycleccc** [comment]
已更新 5.3.15

**Comment by wjw020206** [comment]
> 已更新 5.3.15

目前看是没有这个问题了，感谢作者大大的更新

**Comment by Srhui20** [comment]
最新版本是不是又有这个错误了editorRef.value.setHtml( `<ul><li><span style=\"font-size: 16px;\">123</span></li></ul>` );

<img width="759" height="248" alt="Image" src="https://github.com/user-attachments/assets/cfc829bd-b39c-4c0b-8b75-12060e4e28a5" />
