### ISSUE TITLE
Bug: 表格宽度自适应行为与原版 WangEditor 不一致

### ISSUE THREAD

**Issue by wjw020206** [wangeditor-next/wangEditor-next#82]
## bug 描述

- wangeditor@5.1.23
![wangeditor](https://github.com/user-attachments/assets/37be02e3-9063-4280-bc9a-72d3612c5c33)

- wangeditor-next@5.3.14
![wangEditor-next](https://github.com/user-attachments/assets/a813e295-7e5c-4194-958d-e2bcc74f4af3)

## 你预期的样子是？

宽度自适应时不会出现滚动条

## 系统和浏览器及版本号

- Windows 10
- Microsoft Edge 127.0.2651.86

## wangEditor-next 版本

"@wangeditor-next/editor": "^5.3.14"
"@wangeditor-next/editor-for-vue2": "^1.0.2"

## demo 能否复现该 bug ？

能

**Comment by wjw020206** [comment]
这个问题导致了我在刚才弄表格的时候宽度是好好的，然后保存到后台，再查看的时候就出现表格的滚动条
![问题](https://github.com/user-attachments/assets/ce16b976-f29f-4876-86ca-7981a36f4798)

## 在线 demo
在 demo 中表格我创建是10 x 10，并且设置了宽度自适应，把生成的HTML放入异步获取HTML内容里面，可以复现这个问题
https://stackblitz.com/edit/vue2-vite-starter-cgtqrz?file=README.md

**Comment by cycleccc** [comment]
这里应该是两个问题
https://github.com/cycleccc/wangEditor-next/blob/72784cfe396f4ca4de304366edf93958c889aa30/packages/table-module/src/module/menu/InsertTable.ts#L16
1. 最小宽度设置，原 wangeditor 设置的是 30，而 wangeditor-next 设置的 60，应该做成可配置的
2. 没有保存宽度样式
这两个都得改改

**Comment by cycleccc** [comment]
已在 [5.4.1](https://www.npmjs.com/package/@wangeditor-next/editor/v/5.4.1) 实现

**Comment by wjw020206** [comment]
> 已在 [5.4.1](https://www.npmjs.com/package/@wangeditor-next/editor/v/5.4.1) 实现

经过测试确实没有问题了，感谢
